_plans:
  core_unit_test_implementation:
    created_at: '2025-09-10T18:31:20.783978'
    description: Methodical implementation of unit tests for @agentc/realtime-core
      package, incorporating test strategies and review feedback. Focus on high-value
      tests with manageable complexity.
    id: 3a831a1e-799d-48a1-b638-cb4095e4a8da
    lessons_learned: []
    tasks:
      04640786-aa35-47f7-81b3-35649d1223c6:
        child_tasks:
        - 68d4fc3c-c353-4ac1-a284-24330d3cdf37
        - 19aa418e-7ad5-475d-abaa-b365d9ed37cb
        - 4869173e-87a6-41cd-aa4f-0bff86404656
        - 240fe207-7559-49bd-9d20-1a781873ecba
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:33:42.682991'
        description: Components that need simplified testing approaches, focusing
          on integration over extensive unit tests
        id: 04640786-aa35-47f7-81b3-35649d1223c6
        parent_id: null
        priority: low
        requires_completion_signoff: 'true'
        sequence: 4
        title: 'Phase 3: Simplified Approach Components'
        updated_at: '2025-09-10T18:33:42.682992'
      11028537-42e0-4ee8-a92d-88cccacc2ad1:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:31:51.176316'
        description: 'Create standardized mocks for:

          - WebSocket API

          - AudioContext and Web Audio API (simplified Level 1 stubs)

          - MediaStream and getUserMedia

          - Fetch API for auth'
        id: 11028537-42e0-4ee8-a92d-88cccacc2ad1
        parent_id: 872b09b8-0892-454f-a94b-01a844718d15
        priority: high
        requires_completion_signoff: 'true'
        sequence: 2
        title: Create browser API mocks
        updated_at: '2025-09-10T18:31:51.176318'
      19aa418e-7ad5-475d-abaa-b365d9ed37cb:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:34:03.557279'
        description: Add format compatibility tests. Test voice selection, special
          modes (none/avatar), event handling.
        id: 19aa418e-7ad5-475d-abaa-b365d9ed37cb
        parent_id: 04640786-aa35-47f7-81b3-35649d1223c6
        priority: low
        requires_completion_signoff: 'true'
        sequence: 2
        title: VoiceManager tests
        updated_at: '2025-09-10T18:34:03.557280'
      1cffada2-0d17-410f-9534-150f2bdea189:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:34:57.141406'
        description: Minimize unit tests due to AudioWorklet complexity. Focus on
          integration tests instead. Only test initialization and message passing.
        id: 1cffada2-0d17-410f-9534-150f2bdea189
        parent_id: 9c10e87e-2411-426f-b149-6588c5f36cbb
        priority: low
        requires_completion_signoff: 'true'
        sequence: 2
        title: AudioProcessor tests (minimal)
        updated_at: '2025-09-10T18:34:57.141407'
      240fe207-7559-49bd-9d20-1a781873ecba:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:34:24.829527'
        description: Simple component. Test state tracking, session management, integration
          boundaries.
        id: 240fe207-7559-49bd-9d20-1a781873ecba
        parent_id: 04640786-aa35-47f7-81b3-35649d1223c6
        priority: low
        requires_completion_signoff: 'true'
        sequence: 4
        title: AvatarManager tests
        updated_at: '2025-09-10T18:34:24.829527'
      242ccc77-2540-4e94-9a71-df22955301d6:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:34:46.783888'
        description: Consolidate test files, simplify mocks to Level 1 stubs. Test
          permission handling, state transitions, event emission. Skip complex AudioProcessor
          internals.
        id: 242ccc77-2540-4e94-9a71-df22955301d6
        parent_id: 9c10e87e-2411-426f-b149-6588c5f36cbb
        priority: low
        requires_completion_signoff: 'true'
        sequence: 1
        title: AudioService tests (simplified)
        updated_at: '2025-09-10T18:34:46.783889'
      4869173e-87a6-41cd-aa4f-0bff86404656:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:34:13.849417'
        description: Add URL validation suite. Test config merging, defaults, validation
          rules.
        id: 4869173e-87a6-41cd-aa4f-0bff86404656
        parent_id: 04640786-aa35-47f7-81b3-35649d1223c6
        priority: low
        requires_completion_signoff: 'true'
        sequence: 3
        title: ClientConfig tests
        updated_at: '2025-09-10T18:34:13.849418'
      5b33e630-a540-448d-85e6-54516a1d62e6:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:33:32.840656'
        description: Well-structured approach. Test exponential backoff, jitter, state
          transitions, max attempts. Use fake timers.
        id: 5b33e630-a540-448d-85e6-54516a1d62e6
        parent_id: ceac644c-e3d8-41ed-905b-2aeb408b340e
        priority: medium
        requires_completion_signoff: 'true'
        sequence: 4
        title: ReconnectionManager tests
        updated_at: '2025-09-10T18:33:32.840656'
      5eab2b2c-6227-4c42-bbc5-68b0ade1edf1:
        child_tasks:
        - 70cdd5e3-822e-4092-9e8b-bbf2f2a34c7b
        - d7e9975f-e56a-49be-81a7-738465850c08
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: Quinn identified that we need a separate strategy for integration
          tests to cover end-to-end flows, component interactions during edge cases,
          real browser API behavior (especially audio), and network simulation scenarios.
        created_at: '2025-09-10T18:35:19.105846'
        description: Define and implement integration tests for end-to-end flows and
          component interactions
        id: 5eab2b2c-6227-4c42-bbc5-68b0ade1edf1
        parent_id: null
        priority: medium
        requires_completion_signoff: 'true'
        sequence: 6
        title: 'Phase 5: Integration Test Strategy'
        updated_at: '2025-09-10T18:35:19.105847'
      68d4fc3c-c353-4ac1-a284-24330d3cdf37:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:33:53.270227'
        description: Use integration tests primarily. Unit tests only for critical
          coordination logic. Mock all managers with simple stubs.
        id: 68d4fc3c-c353-4ac1-a284-24330d3cdf37
        parent_id: 04640786-aa35-47f7-81b3-35649d1223c6
        priority: low
        requires_completion_signoff: 'true'
        sequence: 1
        title: RealtimeClient tests (minimal unit)
        updated_at: '2025-09-10T18:33:53.270227'
      70cdd5e3-822e-4092-9e8b-bbf2f2a34c7b:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:35:30.043685'
        description: 'Document strategy for integration tests covering:

          - End-to-end connection and chat flows

          - Audio recording to playback pipeline

          - Error recovery scenarios

          - Network simulation (disconnects, latency)

          - Browser environment events (sleep/wake, tab switching)'
        id: 70cdd5e3-822e-4092-9e8b-bbf2f2a34c7b
        parent_id: 5eab2b2c-6227-4c42-bbc5-68b0ade1edf1
        priority: medium
        requires_completion_signoff: 'true'
        sequence: 1
        title: Create integration test strategy document
        updated_at: '2025-09-10T18:35:30.043686'
      7ded67c5-0491-4b9b-b39d-bf56c1daef57:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:33:22.942624'
        description: Simplify mock complexity first, then test event coordination,
          message building, state management. Focus on behavior not implementation.
        id: 7ded67c5-0491-4b9b-b39d-bf56c1daef57
        parent_id: ceac644c-e3d8-41ed-905b-2aeb408b340e
        priority: medium
        requires_completion_signoff: 'true'
        sequence: 3
        title: EventStreamProcessor tests (simplified)
        updated_at: '2025-09-10T18:33:22.942625'
      7e437968-2019-4d24-a918-05dd82919d37:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:32:42.123983'
        description: Best-balanced audio strategy. Test streaming control, turn awareness,
          statistics tracking. Use simple stubs for AudioService.
        id: 7e437968-2019-4d24-a918-05dd82919d37
        parent_id: a57ee679-8bbe-4d5e-b883-4c6fc0842d7f
        priority: high
        requires_completion_signoff: 'true'
        sequence: 4
        title: AudioAgentCBridge tests
        updated_at: '2025-09-10T18:32:42.123984'
      872b09b8-0892-454f-a94b-01a844718d15:
        child_tasks:
        - cdad2eb4-c2cb-427e-b2c7-895540d47509
        - 11028537-42e0-4ee8-a92d-88cccacc2ad1
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:31:30.021224'
        description: Create shared test utilities and helpers before implementing
          individual tests
        id: 872b09b8-0892-454f-a94b-01a844718d15
        parent_id: null
        priority: high
        requires_completion_signoff: 'true'
        sequence: 1
        title: 'Phase 0: Test Infrastructure Setup'
        updated_at: '2025-09-10T18:31:30.021225'
      88a3d4e9-e6bc-44b7-8ff2-159fcf77fffd:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:33:02.428085'
        description: Important state management. Test session lifecycle, message accumulation,
          capacity management, pagination. Add concurrency tests for race conditions.
        id: 88a3d4e9-e6bc-44b7-8ff2-159fcf77fffd
        parent_id: ceac644c-e3d8-41ed-905b-2aeb408b340e
        priority: medium
        requires_completion_signoff: 'true'
        sequence: 1
        title: SessionManager tests
        updated_at: '2025-09-10T18:33:02.428086'
      9c10e87e-2411-426f-b149-6588c5f36cbb:
        child_tasks:
        - 242ccc77-2540-4e94-9a71-df22955301d6
        - 1cffada2-0d17-410f-9534-150f2bdea189
        - f0e21a83-4b27-41c2-a8bb-9b2c5d40be17
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: Quinn's review identified that the audio module strategies have mock
          complexity approaching the actual implementation complexity. This is unmaintainable.
          We need to drastically simplify to stub-level mocks for unit tests and move
          timing/quality verification to integration tests.
        created_at: '2025-09-10T18:34:36.320110'
        description: Audio components need major simplification of mock complexity.
          Focus on logic testing, not timing/quality.
        id: 9c10e87e-2411-426f-b149-6588c5f36cbb
        parent_id: null
        priority: low
        requires_completion_signoff: 'true'
        sequence: 5
        title: 'Phase 4: Audio Module (Rework Required)'
        updated_at: '2025-09-10T18:34:36.320111'
      a2161af8-520b-46b6-ac53-92fe2c62aa42:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:32:31.642060'
        description: Foundation component. Test type-safe event handling, listener
          management, memory leak prevention, and error isolation.
        id: a2161af8-520b-46b6-ac53-92fe2c62aa42
        parent_id: a57ee679-8bbe-4d5e-b883-4c6fc0842d7f
        priority: high
        requires_completion_signoff: 'true'
        sequence: 3
        title: EventEmitter tests
        updated_at: '2025-09-10T18:32:31.642061'
      a57ee679-8bbe-4d5e-b883-4c6fc0842d7f:
        child_tasks:
        - d3082461-10ba-4c1d-b0be-11505023c228
        - fe1d2013-351a-4941-98c8-c1b8cf800650
        - a2161af8-520b-46b6-ac53-92fe2c62aa42
        - 7e437968-2019-4d24-a918-05dd82919d37
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:32:00.806002'
        description: Implement tests for simple, critical components that provide
          maximum value with minimal mock complexity
        id: a57ee679-8bbe-4d5e-b883-4c6fc0842d7f
        parent_id: null
        priority: high
        requires_completion_signoff: 'true'
        sequence: 2
        title: 'Phase 1: High-Value, Low-Complexity Tests'
        updated_at: '2025-09-10T18:32:00.806003'
      a90955f3-538e-41ce-82ec-0be7e91c60b9:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:33:12.724413'
        description: Security critical. Test JWT lifecycle, token refresh, timer management.
          MUST include race condition tests for concurrent token refresh attempts.
        id: a90955f3-538e-41ce-82ec-0be7e91c60b9
        parent_id: ceac644c-e3d8-41ed-905b-2aeb408b340e
        priority: high
        requires_completion_signoff: 'true'
        sequence: 2
        title: AuthManager tests
        updated_at: '2025-09-10T18:33:12.724414'
      cdad2eb4-c2cb-427e-b2c7-895540d47509:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:31:40.656022'
        description: 'Create test/shared/ directory with:

          - singleton-helpers.ts for reusable singleton pattern tests

          - mock-builders.ts for common mock factories

          - event-helpers.ts for event assertion utilities

          - timer-helpers.ts for fake timer utilities'
        id: cdad2eb4-c2cb-427e-b2c7-895540d47509
        parent_id: 872b09b8-0892-454f-a94b-01a844718d15
        priority: high
        requires_completion_signoff: 'true'
        sequence: 1
        title: Create shared test utilities
        updated_at: '2025-09-10T18:31:40.656023'
      ceac644c-e3d8-41ed-905b-2aeb408b340e:
        child_tasks:
        - 88a3d4e9-e6bc-44b7-8ff2-159fcf77fffd
        - a90955f3-538e-41ce-82ec-0be7e91c60b9
        - 7ded67c5-0491-4b9b-b39d-bf56c1daef57
        - 5b33e630-a540-448d-85e6-54516a1d62e6
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:32:51.717651'
        description: Implement tests for core business logic components with moderate
          complexity
        id: ceac644c-e3d8-41ed-905b-2aeb408b340e
        parent_id: null
        priority: medium
        requires_completion_signoff: 'true'
        sequence: 3
        title: 'Phase 2: Core Business Logic Tests'
        updated_at: '2025-09-10T18:32:51.717651'
      d3082461-10ba-4c1d-b0be-11505023c228:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:32:11.351442'
        description: Critical infrastructure component. Test connection lifecycle,
          message handling, heartbeat mechanism, and error scenarios. Use Level 1-2
          mocks only.
        id: d3082461-10ba-4c1d-b0be-11505023c228
        parent_id: a57ee679-8bbe-4d5e-b883-4c6fc0842d7f
        priority: high
        requires_completion_signoff: 'true'
        sequence: 1
        title: WebSocketManager tests
        updated_at: '2025-09-10T18:32:11.351443'
      d7e9975f-e56a-49be-81a7-738465850c08:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:35:41.124661'
        description: 'Implement integration tests for:

          - Complete connection lifecycle with auth

          - Message flow from send to receive

          - Audio pipeline end-to-end

          - Reconnection with state recovery

          - Multi-component error cascades'
        id: d7e9975f-e56a-49be-81a7-738465850c08
        parent_id: 5eab2b2c-6227-4c42-bbc5-68b0ade1edf1
        priority: medium
        requires_completion_signoff: 'true'
        sequence: 2
        title: Implement critical integration tests
        updated_at: '2025-09-10T18:35:41.124662'
      f0e21a83-4b27-41c2-a8bb-9b2c5d40be17:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:35:08.154511'
        description: Test logic not timing. Use integration tests for playback quality.
          Test queue management, voice model handling, state transitions with simple
          stubs.
        id: f0e21a83-4b27-41c2-a8bb-9b2c5d40be17
        parent_id: 9c10e87e-2411-426f-b149-6588c5f36cbb
        priority: low
        requires_completion_signoff: 'true'
        sequence: 3
        title: AudioOutputService tests (logic only)
        updated_at: '2025-09-10T18:35:08.154512'
      fe1d2013-351a-4941-98c8-c1b8cf800650:
        child_tasks: []
        completed: false
        completion_report: null
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-10T18:32:21.419060'
        description: Simple component with perfect scope. Test turn state transitions,
          event handling, and cleanup. Should achieve 100% coverage easily.
        id: fe1d2013-351a-4941-98c8-c1b8cf800650
        parent_id: a57ee679-8bbe-4d5e-b883-4c6fc0842d7f
        priority: high
        requires_completion_signoff: 'true'
        sequence: 2
        title: TurnManager tests
        updated_at: '2025-09-10T18:32:21.419061'
    title: Core Package Unit Test Implementation Plan
    updated_at: '2025-09-10T18:35:41.124683'
current_plan: core_unit_test_implementation
