_plans:
  demo_cleanup:
    created_at: '2025-09-04T18:38:29.414892'
    description: Critical cleanup to remove all components from the demo app that
      should be imported from SDK packages. The demo should demonstrate our SDK, not
      reimplement it.
    id: 837125df-d8ea-4d09-88f1-03ad9c20a93e
    lessons_learned: []
    tasks:
      0d149b35-c8d5-4191-9d98-052c681c61a0:
        child_tasks: []
        completed: true
        completion_report: Successfully updated all 25 demo files to import from @agentc/realtime-ui
          instead of local components. Demo now properly consumes SDK packages. Build
          requires dependency installation in UI package.
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-04T18:39:31.347861'
        description: Refactor all imports to use components from @agentc/realtime-ui
          and @agentc/realtime-react
        id: 0d149b35-c8d5-4191-9d98-052c681c61a0
        parent_id: null
        priority: high
        requires_completion_signoff: 'true'
        sequence: 4
        title: Update demo to use SDK packages
        updated_at: '2025-09-04T19:41:15.413434'
      7af234bf-8a9a-4249-905c-cb0d376505ca:
        child_tasks: []
        completed: true
        completion_report: Successfully deleted entire components/ui/ folder with
          40+ shadcn components. 30 components were pure bloat (never used), 16 component
          groups were actually needed and have been moved to SDK.
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-04T18:39:15.690836'
        description: Delete the entire components/ui folder with 40+ shadcn components
          that don't belong in a demo
        id: 7af234bf-8a9a-4249-905c-cb0d376505ca
        parent_id: null
        priority: high
        requires_completion_signoff: 'true'
        sequence: 3
        title: Remove duplicate UI library components
        updated_at: '2025-09-04T19:27:12.104960'
      b7bf4d2c-acba-467d-87b0-094cb24ea799:
        child_tasks: []
        completed: true
        completion_report: "Phase 2 complete:\n- Added 16 essential UI components\
          \ to @agentc/realtime-ui \n- Moved useOutputMode hook to @agentc/realtime-react\n\
          - All components follow CenSuite design patterns\nNote: UI package needs\
          \ dependency installation for full functionality"
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-04T18:39:00.249899'
        description: Transfer chat, input, and other reusable components to the UI
          package where they belong
        id: b7bf4d2c-acba-467d-87b0-094cb24ea799
        parent_id: null
        priority: high
        requires_completion_signoff: 'true'
        sequence: 2
        title: Move reusable UI components to @agentc/realtime-ui
        updated_at: '2025-09-04T19:26:54.476250'
      e18ed163-d2c2-42c7-8ba7-e656f5c5d40c:
        child_tasks: []
        completed: true
        completion_report: 'Audit complete. Found:

          - 42+ UI components to DELETE (entire ui/ folder)

          - 15 components to move to @agentc/realtime-ui

          - 1 hook (useOutputMode) to move to @agentc/realtime-react

          - 20 components correctly demo-specific and should stay'
        completion_signoff_by: null
        context: ''
        created_at: '2025-09-04T18:38:45.491316'
        description: Identify which components should be moved to SDK packages vs
          deleted vs kept as demo-specific
        id: e18ed163-d2c2-42c7-8ba7-e656f5c5d40c
        parent_id: null
        priority: high
        requires_completion_signoff: 'true'
        sequence: 1
        title: Audit and categorize all demo components
        updated_at: '2025-09-04T18:59:52.399536'
    title: Demo App Cleanup - Remove Internal Components
    updated_at: '2025-09-04T19:41:15.413458'

current_plan: outputselector_fix
