version: '3.8'

services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
      # Use BuildKit for better caching
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: agentc-realtime-demo:latest
    container_name: agentc-realtime-demo
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_APP_URL=https://localhost:5173
      - AGENT_C_API_URL=https://localhost:8000
      - NEXT_PUBLIC_AGENTC_API_URL=wss://localhost:8000
    restart: unless-stopped
    # Healthcheck for the Next.js app
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  
# Optional: Add a development configuration
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up