'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_WorkflowManager_Quote_Farm

    '''<summary>
    '''ctlEffectiveDateChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEffectiveDateChecker As Global.IFM.VR.Web.ctlEffectiveDateChecker

    '''<summary>
    '''ctl_Farm_Basic_Policy_Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Farm_Basic_Policy_Info As Global.IFM.VR.Web.ctl_Farm_Basic_Policy_Info

    '''<summary>
    '''ctlUWQuestionsPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlUWQuestionsPopup As Global.IFM.VR.Web.ctlUWQuestionsPopup

    '''<summary>
    '''ctlDisplayDiamondRatingErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDisplayDiamondRatingErrors As Global.IFM.VR.Web.ctlDisplayDiamondRatingErrors

    '''<summary>
    '''ctlTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlTreeView As Global.IFM.VR.Web.ctlTreeView

    '''<summary>
    '''ctl_Insured_Applicant_Manager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Insured_Applicant_Manager As Global.IFM.VR.Web.ctl_Insured_Applicant_Manager

    '''<summary>
    '''ctlFarmPolicyCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlFarmPolicyCoverages As Global.IFM.VR.Web.ctlFarmPolicyCoverages

    '''<summary>
    '''ctlFarmLocationCoverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlFarmLocationCoverage As Global.IFM.VR.Web.ctlFarmLocationCoverage

    '''<summary>
    '''ctlQuoteSummary_Farm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlQuoteSummary_Farm As Global.IFM.VR.Web.ctlQuoteSummary_Farm

    '''<summary>
    '''ctlIRPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlIRPM As Global.IFM.VR.Web.ctlIRPM

    '''<summary>
    '''ctlFarmPersonalProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlFarmPersonalProperty As Global.IFM.VR.Web.ctlFarmPersonalProperty

    '''<summary>
    '''ctlIMRVWatercraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlIMRVWatercraft As Global.IFM.VR.Web.ctlIMRVWatercraft

    '''<summary>
    '''ctl_Comm_NewQuoteForClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Comm_NewQuoteForClient As Global.IFM.VR.Web.ctl_Comm_NewQuoteForClient

    '''<summary>
    '''ctlPolicyHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPolicyHistory As Global.IFM.VR.Web.ctlPolicyHistory

    '''<summary>
    '''ctlBillingInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlBillingInfo As Global.IFM.VR.Web.ctlBillingInfo

    '''<summary>
    '''ctl_AttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AttachmentUpload As Global.IFM.VR.Web.ctl_AttachmentUpload
End Class
