'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlFarmInlandMarine

    '''<summary>
    '''dvInlandMarineInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvInlandMarineInput As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblInlandMarineHdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInlandMarineHdr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIMChosen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIMChosen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkClearInland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClearInland As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSaveinland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveinland As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlRoundMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRoundMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRoundMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRoundMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlInlandMarineCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInlandMarineCoverages As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlIMJewelry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIMJewelry As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkIMJewelry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIMJewelry As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblIMJewelry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIMJewelry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvIMJewelryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvIMJewelryLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblIMJewelryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIMJewelryLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIMJewelryDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIMJewelryDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlJewelry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlJewelry As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddIMJewelryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddIMJewelryLimit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlJewelInVault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlJewelInVault As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkJewelInVault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkJewelInVault As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblJewelInVault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJewelInVault As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvJewelInVaultLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvJewelInVaultLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblJewelryVaultLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJewelryVaultLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJewelryVaultDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJewelryVaultDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlJewelInVault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlJewelInVault As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddJewleryInVault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddJewleryInVault As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlAntiquesBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAntiquesBreak As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkAntiquesBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAntiquesBreak As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAntiquesBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiquesBreak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvAntiquesBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAntiquesBreakLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAntiquesBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiquesBreakLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAntiquesBreakDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiquesBreakDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlAntiquesBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlAntiquesBreak As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddAntiquesBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddAntiquesBreak As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlAntiquesNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAntiquesNoBreak As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkAntiquesNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAntiquesNoBreak As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAntiquesNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiquesNoBreak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvAntiquesNoBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvAntiquesNoBreakLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAntiquesNoBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiquesNoBreakLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAntiquesNoBreakDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiquesNoBreakDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlAntiquesNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlAntiquesNoBreak As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddAntiquesNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddAntiquesNoBreak As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlCollectBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCollectBreak As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkCollectBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCollectBreak As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCollectBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCollectBreak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvCollectBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCollectBreakLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCollectBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCollectBreakLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCollectBreakDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCollectBreakDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlCollectBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCollectBreak As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddCollectBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCollectBreak As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlCollectNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCollectNoBreak As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkCollectNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCollectNoBreak As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCollectNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCollectNoBreak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvCollectNoBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCollectNoBreakLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCollectNoBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCollectNoBreakLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCollectNoBreakDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCollectNoBreakDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlCollectNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCollectNoBreak As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddCollectNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCollectNoBreak As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlCameras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCameras As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkCameras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCameras As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCameras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCameras As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvCamerasLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCamerasLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCamerasLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCamerasLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCamerasDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCamerasDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlCameras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCameras As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddCameras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddCameras As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlComputers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlComputers As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkComputers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkComputers As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblComputers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComputers As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvComputersLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvComputersLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblComputersLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComputersLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComputersDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComputersDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlComputers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlComputers As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddComputers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddComputers As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlFABreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFABreak As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkFABreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFABreak As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblFABreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFABreak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvFABreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFABreakLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblArtsBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArtsBreakLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblArtsBreakDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArtsBreakDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlArtsBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlArtsBreak As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddFABreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddFABreak As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlFANoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFANoBreak As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkFANoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFANoBreak As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblFANoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFANoBreak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvFANoBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFANoBreakLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblArtsNoBreakLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArtsNoBreakLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblArtsNoBreakDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArtsNoBreakDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlArtsNoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlArtsNoBreak As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddFANoBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddFANoBreak As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlFurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFurs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkFurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFurs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblFurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFurs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvFursLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFursLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFursLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFursLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFursDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFursDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlFurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlFurs As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddFurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddFurs As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlGuns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGuns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkGuns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGuns As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblGuns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGuns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvGunsLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvGunsLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGunsLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGunsLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGunsDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGunsDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlGuns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlGuns As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddGuns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddGuns As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlHearing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHearing As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkHearing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHearing As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblHearing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHearing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvHearingLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvHearingLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblHearingLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHearingLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHearingDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHearingDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlHearing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlHearing As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddHearing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddHearing As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlIrrigationNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIrrigationNamed As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkIrrigationNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIrrigationNamed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblIrrigationNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIrrigationNamed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvIrrigationNamedLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvIrrigationNamedLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblIrrigationNamedLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIrrigationNamedLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIrrigationNamedDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIrrigationNamedDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlIrrigationNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlIrrigationNamed As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddIrrigationNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddIrrigationNamed As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlIrrigationSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIrrigationSpecial As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkIrrigationSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIrrigationSpecial As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblIrrigationSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIrrigationSpecial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvIrrigationSpecialLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvIrrigationSpecialLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblIrrigationSpecialLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIrrigationSpecialLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIrrigationSpecialDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIrrigationSpecialDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlIrrigationSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlIrrigationSpecial As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddIrrigationSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddIrrigationSpecial As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlRadioCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRadioCB As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkRadioCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRadioCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblRadioCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRadioCB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvRadioCBLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvRadioCBLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRadioCBLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRadioCBLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRadioCBDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRadioCBDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlRadioCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlRadioCB As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddRadioCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddRadioCB As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlRadiosFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRadiosFM As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkRadiosFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRadiosFM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblRadiosFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRadiosFM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvRadiosFMLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvRadiosFMLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRadiosFMLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRadiosFMLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRadiosFMDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRadiosFMDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlRadiosFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlRadiosFM As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddRadiosFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddRadiosFM As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlReproductiveNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReproductiveNamed As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkReproductiveNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReproductiveNamed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblReproductiveNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReproductiveNamed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvReproductiveNamedLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvReproductiveNamedLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReproductiveNamedLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReproductiveNamedLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReproductiveNamedDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReproductiveNamedDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlReproductiveNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlReproductiveNamed As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddReproductiveNamed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddReproductiveNamed As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlReproductiveSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReproductiveSpecial As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkReproductiveSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReproductiveSpecial As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblReproductiveSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReproductiveSpecial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvReproductiveSpecialLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvReproductiveSpecialLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReproductiveSpecialLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReproductiveSpecialLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReproductiveSpecialDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReproductiveSpecialDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlReproductiveSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlReproductiveSpecial As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddReproductiveSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddReproductiveSpecial As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMobile As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMobile As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMobile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvMobileLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvMobileLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMobileLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMobileLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMobileDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMobileDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlMobile As Global.IFM.VR.Web.ctlInlandMarineIncreasedLimit

    '''<summary>
    '''lnkAddMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddMobile As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hiddenSelectedIMCoverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenSelectedIMCoverage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenIM As Global.System.Web.UI.WebControls.HiddenField
End Class
