'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlFarmLocation
    
    '''<summary>
    '''lblMainHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkNewLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNewLocation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkDeleteLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDeleteLocation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkClearLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClearLocation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkSaveLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveLocation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''farmLocationDataContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents farmLocationDataContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctlPropertyAdditionalQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPropertyAdditionalQuestions As Global.IFM.VR.Web.ctlPropertyAdditionalQuestions
    
    '''<summary>
    '''ctlProperty_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlProperty_Address As Global.IFM.VR.Web.ctlProperty_Address
    
    '''<summary>
    '''ctlPersLiabGL9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPersLiabGL9 As Global.IFM.VR.Web.ctlFARPersonalLiabilityGL9
    
    '''<summary>
    '''ctlResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlResidence As Global.IFM.VR.Web.ctlResidence
    
    '''<summary>
    '''dvInitRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvInitRes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''h3InitResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents h3InitResidence As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblInitResidenceHdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitResidenceHdr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkAddNewResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddNewResidence As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''hiddenActiveResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenActiveResidence As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ctl_FarBuildingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_FarBuildingList As Global.IFM.VR.Web.ctl_FarBuildingList
    
    '''<summary>
    '''btnAddLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddLocation As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hiddenLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenLocation As Global.System.Web.UI.WebControls.HiddenField
End Class
