'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class cov_Contractor
    
    '''<summary>
    '''ceSubGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ceSubGroup As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''divContractorOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContractorOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkContractorsEquipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContractorsEquipment As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''clearButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divContractorDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContractorDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''ceDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ceDeductible As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ceCoinsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ceCoinsurance As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cov_Contractor_Item control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_Contractor_Item As Global.IFM.VR.Web.cov_Contractor_Item
    
    '''<summary>
    '''chkUnscheduledTools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnscheduledTools As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divCeUnscheduledTools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCeUnscheduledTools As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtUnscheduledToolsLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnscheduledToolsLimit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''coverageMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coverageMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
