'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class cov_InstallationFloater
    
    '''<summary>
    '''cpSubGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpSubGroup As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''divInstallationFloaterOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInstallationFloaterOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkInstallationFloater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInstallationFloater As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''clearButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divInstallationFloaterDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInstallationFloaterDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''ifDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifDeductible As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ifCoinsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifCoinsurance As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''withoutPackageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents withoutPackageLabel As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''withoutPackage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents withoutPackage As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtJobSiteLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobSiteLimit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCatLimitWithout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCatLimitWithout As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''withPackageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents withPackageLabel As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''withPackage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents withPackage As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtIncludedJobSiteLmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncludedJobSiteLmit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIncreasedLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncreasedLimit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCatLimitWith control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCatLimitWith As Global.System.Web.UI.WebControls.TextBox
End Class
