'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class cov_Transportation
    
    '''<summary>
    '''cpSubGroup_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpSubGroup_FoodManuf As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''divTransportationOption_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportationOption_FoodManuf As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkTransportation_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTransportation_FoodManuf As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''clearButton_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearButton_FoodManuf As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divTransportationDetail_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportationDetail_FoodManuf As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table2_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2_FoodManuf As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trDeductible_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDeductible_FoodManuf As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtDescription_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription_FoodManuf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimitPerVehicle_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimitPerVehicle_FoodManuf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIncreasedLimit_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncreasedLimit_FoodManuf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTotalVehicleLimit_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalVehicleLimit_FoodManuf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumOfVehicles_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumOfVehicles_FoodManuf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCatLimit_FoodManuf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCatLimit_FoodManuf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cpSubGroup_Normal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpSubGroup_Normal As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''divTransportationOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportationOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkTransportation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTransportation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''clearButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divTransportationDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportationDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDeductible As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimitPerVehicle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimitPerVehicle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumOfVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumOfVehicles As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCatLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCatLimit As Global.System.Web.UI.WebControls.TextBox
End Class
