'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_InlandMarineAssignedAI

    '''<summary>
    '''lblExpanderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpanderText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divAiEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAiEntry As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlIMType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIMType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlGAIDescriptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGAIDescriptions As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdnAiDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAiDescription As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlGAILimitLossPayeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGAILimitLossPayeeName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlGAILimitLossPayeeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGAILimitLossPayeeType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlGAILimitATMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGAILimitATMA As Global.System.Web.UI.WebControls.DropDownList
End Class
