'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_BOP_ENDO_Location

    '''<summary>
    '''lblAccordHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccordHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNew As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDelete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClear As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divContents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ctlProperty_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlProperty_Address As Global.IFM.VR.Web.ctlProperty_Address

    '''<summary>
    '''ctl_BOP_ENDO_Location_Coverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_BOP_ENDO_Location_Coverages As Global.IFM.VR.Web.ctl_BOP_ENDO_Location_Coverages

    '''<summary>
    '''ctl_BOP_ENDO_BuildingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_BOP_ENDO_BuildingList As Global.IFM.VR.Web.ctl_BOP_ENDO_BuildingList

    '''<summary>
    '''btnAddBuilding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddBuilding As Global.System.Web.UI.WebControls.Button
End Class
