using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IFM.DataServices.API.ResponseObjects.Fiserv
{
    [System.Serializable]
    public class FiservResult // : Common.ServiceResult
    {
        public bool Success { get; set; }
    }
    [System.Serializable]
    public class FiservAddWalletItemResult : FiservResult // : FiservServiceResult
    {
        public int FiservWalletItemId { get; set; } //generated by IFM after Create
        public string FundingAccountToken { get; set; } //generated by Fiserv (their key)
        public int FiservWalletId { get; set; } //generated by IFM after Creation of 1st WalletItem
        public string FundingMethod { get; set; } //set by Fiserv based on the card/bank information; also returned by iframe
        public string FundingAccountLastFourDigit { get; set; } //set by Fiserv based on the card/bank information; also returned by iframe
    }
    [System.Serializable]
    public class FiservUpdateWalletItemResult : FiservResult // : FiservServiceResult
    {
        //public string FundingAccountToken { get; set; } //generated by Fiserv (their key)
    }
    [System.Serializable]
    public class FiservDeleteWalletItemResult : FiservResult // : FiservServiceResult
    {

    }
    [System.Serializable]
    public class FiservAddScheduledPaymentResult : FiservResult // : FiservServiceResult
    {
        public int FiservScheduledPaymentId { get; set; } //generated by IFM after Create
        public string ReferenceId { get; set; } //generated by Fiserv (their key)
    }
    [System.Serializable]
    public class FiservUpdateScheduledPaymentResult : FiservResult // : FiservServiceResult
    {

    }
    [System.Serializable]
    public class FiservDeleteScheduledPaymentResult : FiservResult // : FiservServiceResult
    {

    }
    [System.Serializable]
    public class FiservUpdateWalletResult : FiservResult // : FiservServiceResult
    {

    }
    //added 7/30/2020
    [System.Serializable]
    public class FiservUpdateWalletsResult : FiservResult // : FiservServiceResult
    {

    }
    //added 9/26/2024
    [System.Serializable]
    public class FiservCalculateFeeResult : FiservResult
    {
        public string FeeAmount { get; set; } //string instead of double so it can go to database as NULL when not used (property set to emptyString) //added 10/16/2024
        public string Fiserv_AuthToken { get; set; } //obtained for use w/ iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public string Fiserv_SessionToken { get; set; } //obtained for use w/ iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public int Fiserv_SessionId { get; set; } //obtained while getting tokens used w/ iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public string Fiserv_FundingAccountToken { get; set; } //obtained from iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public bool BackupLogicUsedToCalculateFee { get; set; }
        public string OriginalFeeAmountFromFiserv { get; set; }

    }

}
