# PLANE API - FINAL WORKING CONFIGURATION
# Date: 2025-10-15
# Status: ✅ VERIFIED WORKING

plane:
  # Instance Configuration
  instance_url: "http://localhost"
  workspace_slug: "agent_c"
  workspace_id: "0bc2932a-4bec-47c2-b544-b2d8bd94b79b"
  workspace_name: "Agent_C"
  
  # Authentication Method: Cookie-based Session
  authentication:
    method: "session_cookies"
    required_cookies:
      - "session-id"           # PRIMARY - Django session ID
      - "agentc-auth-token"    # JWT token for client
      - "csrftoken"            # CSRF protection
      - "ajs_anonymous_id"     # Analytics (optional)
    
    # Current Cookie Values (expires: varies)
    session_id: "my5jxtxf45248zxyapvhh8hcbpfh9twp4tw6u491dzewnfnjc2wapwccwanxetpg5d00u8amq78zvjwdetdhdo8x8p8p3ps6xlbbl1nm4dvg9c59aj7ehuq3adahedna"
    agentc_auth_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVzZXIiOnsidXNlcl9pZCI6ImFkbWluIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImNoYW5nZW1lQGNlbnRyaWNjb25zdWx0aW5nLmNvbSIsImZpcnN0X25hbWUiOiJBZG1pbiIsImxhc3RfbmFtZSI6IlVzZXIiLCJpc19hY3RpdmUiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImdyb3VwcyI6W10sImNyZWF0ZWRfYXQiOiIyMDI1LTA5LTIzVDA3OjE0OjA3LjU0OTc2MiIsImxhc3RfbG9naW4iOm51bGx9LCJleHAiOjE3NjMwMzY4NjYsImlhdCI6MTc2MDM1ODQ2Nn0.bAzdpE0_siX_aBalWpYdGa-phULkb2WCFESx95BAHRk"
    csrftoken: "o4tAHfTcpMvysGKLaIEhw1qUS29yrDP1"
    ajs_anonymous_id: "b84a7c10-2aca-4bf2-9579-f281a47c03d5"

  # User Information
  user:
    email: "ethan.booth@centricconsulting.com"
    role: 20  # Workspace role
    
  # API Configuration
  api:
    base_path: "/api"
    timeout: 30
    retry_attempts: 3
    
  # Request Headers (recommended)
  headers:
    Accept: "application/json"
    Content-Type: "application/json"
    Referer: "http://localhost/"

# Verified Endpoints
verified_endpoints:
  workspace_info:
    method: GET
    path: "/api/workspaces/{workspace_slug}/"
    status: ✅ Working
    
  projects_list:
    method: GET
    path: "/api/workspaces/{workspace_slug}/projects/"
    status: ✅ Working
    sample_data:
      - id: "dad9fe27-de38-4dd6-865f-0455e426339a"
        name: "Agent_C"
        identifier: "AC"
    
  user_workspaces:
    method: GET
    path: "/api/users/me/workspaces/"
    status: ✅ Working
    
  user_profile:
    method: GET
    path: "/api/users/me/"
    status: ✅ Working

# Project Information
existing_projects:
  - id: "dad9fe27-de38-4dd6-865f-0455e426339a"
    name: "Agent_C"
    identifier: "AC"
    logo_emoji: "127773"

# Development Status
status:
  authentication: ✅ SOLVED
  workspace_access: ✅ WORKING
  project_access: ✅ WORKING
  ready_for_development: ✅ YES
  
# Next Steps
next_steps:
  1: "Create PLANE client library with cookie authentication"
  2: "Build project management toolset"
  3: "Build issue management toolset"
  4: "Build search toolset"
  5: "Build analytics toolset"
  6: "Implement cookie refresh mechanism"
  7: "Add proper error handling"
  8: "Create configuration templates"
  9: "Write comprehensive tests"
  10: "Integrate with Rupert agent"
