'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_CPR_LocationCoverages

    '''<summary>
    '''divCPRLocationCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCPRLocationCoverages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAccordHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccordHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClear As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divContents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblLocationPropertyDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblLocationPropertyDeductible As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''trLocationPropertyDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLocationPropertyDeductible As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblLocationPropertyDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocationPropertyDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddLocationPropertyDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddLocationPropertyDeductible As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tdLocationPropertyDeductibleInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLocationPropertyDeductibleInfo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdWindHailDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdWindHailDeductible As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblWindHailDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWindHailDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddWindHailDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddWindHailDeductible As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tdWindHailDeductInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdWindHailDeductInfo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''chkEquipmentBreakdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEquipmentBreakdown As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trEquipmentBreakDownInfoRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEquipmentBreakDownInfoRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''hdnAccord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccord As Global.System.Web.UI.WebControls.HiddenField
End Class
