'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlAdditionalInsured

    '''<summary>
    '''dvFarmAddlInsured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFarmAddlInsured As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAIType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAIType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAIType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tblAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblAI As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblAIBusinessReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIBusinessReq As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIBusiness As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAILastReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAILastReq As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAILastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAILastName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIFirstReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIFirstReq As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAIFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIFirstName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAIBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAIBusiness As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAIOr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIOr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAILastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAILastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAIFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAIFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lnkDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDelete As Global.System.Web.UI.WebControls.LinkButton
End Class
