'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlCommercialDataPrefillEntry

    '''<summary>
    '''divCommDataPrefillPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCommDataPrefillPopup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PolicyholderSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyholderSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtBusinessName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusinessName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStreetNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStreetNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStreetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStreetName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAptNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAptNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDBA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDBA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddBusinessType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddBusinessType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddTaxIDType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTaxIDType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFEIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEIN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdnEmailTypeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmailTypeId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPhoneExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddPhoneType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPhoneType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtOtherEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherEntity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBusinessStarted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusinessStarted As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtYearsOfExperience control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtYearsOfExperience As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDescriptionOfOperations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionOfOperations As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOther As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtClientId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdnHasPrefill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnHasPrefill As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnPrefillOrderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPrefillOrderInfo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnHasChangedSinceLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnHasChangedSinceLoad As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnHasChangedSinceLastCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnHasChangedSinceLastCheck As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtPOBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddCityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddCityName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCityName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddStateAbbrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddStateAbbrev As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtGaragedCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGaragedCounty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divAddressMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddressMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LocationSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LocationRepeaterSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationRepeaterSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptLocations As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnCancelPrefill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelPrefill As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddLoc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSavePrefillEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePrefillEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblFocusClientId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFocusClientId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGovStateId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGovStateId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocNumForLastAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocNumForLastAction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocNumWithFocus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocNumWithFocus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnPolicyholderSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPolicyholderSection As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnLocationSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnLocationSection As Global.System.Web.UI.WebControls.HiddenField
End Class
