'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_CPP_ENDO_Property_Locations

    '''<summary>
    '''ctl_CPR_ENDO_LocationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_CPR_ENDO_LocationList As Global.IFM.VR.Web.ctl_CPR_ENDO_LocationList
End Class
