# Example MCP ToolChest Server configuration with SSE transport
server:
  name: "Agent C"
  host: "127.0.0.1"
  port: 8027
  security:
    allowed_tools: ["*"]  # Allow all tools
  # MCP servers to connect to via SSE
  mcp_servers:
    servers:
      # Example of a custom MCP server using SSE transport
      custom_tools:
        transport_type: "sse"
        url: "http://localhost:8008/sse"
        timeout: 30.0

tools:
  # Auto-discover tools from these packages
  discover:
    - "agent_c_tools.tools"

  # Additional tool packages to import
  imports: []

  # Configuration for specific tools (if needed)
  config: {}