# Example MCP ToolChest Server configuration with SSE transport
server:
  name: "Agent C"
  host: "127.0.0.1"
  port: 8027
  security:
    allowed_tools: ["*"]  # Allow all tools
  # MCP servers to connect to via SSE
  mcp_servers:
    servers:
      # Example of a custom MCP server using SSE transport
      custom_tools:
        transport_type: "sse"
        url: "http://localhost:8008/sse"
        timeout: 30.0

tools:
  # Auto-discover tools from these packages
  discover:
    - "agent_c_tools.tools"

  # Additional tool packages to import
  imports: []

  # Configuration for specific tools (if needed)
  config: {}

# =============================================================================
# Web Search Tools Configuration
# =============================================================================
# The following environment variables are required for web search functionality:
#
# Required for Google Search, News, Flights, Events:
# SERPAPI_API_KEY=your_serpapi_key_here
#
# Required for advanced research searches:
# TAVILI_API_KEY=your_tavily_key_here
#
# Required for news-specific searches:
# NEWSAPI_API_KEY=your_newsapi_key_here
#
# Note: DuckDuckGo, Wikipedia, and Hacker News work without API keys
# See src/agent_c_tools/src/agent_c_tools/tools/web_search/.env.example for details