'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_Master_HOM_APP
    
    '''<summary>
    '''ctlDisplayDiamondRatingErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDisplayDiamondRatingErrors As Global.IFM.VR.Web.ctlDisplayDiamondRatingErrors
    
    '''<summary>
    '''ctl_OrderClueAndOrMVR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_OrderClueAndOrMVR As Global.IFM.VR.Web.ctl_OrderClueAndOrMVR
    
    '''<summary>
    '''ctlUWQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlUWQuestions As Global.IFM.VR.Web.ctlUWQuestions
    
    '''<summary>
    '''ctl_AttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AttachmentUpload As Global.IFM.VR.Web.ctl_AttachmentUpload
    
    '''<summary>
    '''ctl_HOM_App_Section control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_HOM_App_Section As Global.IFM.VR.Web.ctl_HOM_App_Section
    
    '''<summary>
    '''ctlQuoteSummary_HOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlQuoteSummary_HOM As Global.IFM.VR.Web.ctlQuoteSummary_HOM
    
    '''<summary>
    '''ctl_ReturnToQuoteSide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_ReturnToQuoteSide As Global.IFM.VR.Web.ctl_ReturnToQuoteSide
End Class
