'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_BOP_ENDO_Coverages

    '''<summary>
    '''divMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkBtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tblCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCoverages As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''chkAdditionalInsured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAdditionalInsured As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trAdditionalInsuredsRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAdditionalInsuredsRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlNumberOfAddlInsureds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberOfAddlInsureds As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkAI_TownhouseAssociates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAI_TownhouseAssociates As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAI_EngineersArchitectsSurveyors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAI_EngineersArchitectsSurveyors As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOwnersLesseesContractorsAutomatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOwnersLesseesContractorsAutomatic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trOwnersLesseesContractorsAutomaticInfoRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOwnersLesseesContractorsAutomaticInfoRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkWaiverOfSubrogation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWaiverOfSubrogation As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trWaiverOfSubroInfoRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trWaiverOfSubroInfoRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkOwnersLesseesContractorsWithAddlInsuredReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOwnersLesseesContractorsWithAddlInsuredReq As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOwnersLesseesContractorsCompletedOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOwnersLesseesContractorsCompletedOps As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trNumberOfAITextboxRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNumberOfAITextboxRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtNumOfAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumOfAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trOwnersLesseesContractorsCompletedOpsInfoRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOwnersLesseesContractorsCompletedOpsInfoRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkCLIWrapper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCLIWrapper As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkCLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCLI As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trCLIRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCLIRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkEmployeeBenefitsLiability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEmployeeBenefitsLiability As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trEmployeeBenefitsRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEmployeeBenefitsRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtEBLNumberOfEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEBLNumberOfEmployees As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkEPLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEPLI As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trEPLIRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEPLIRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblRetroactiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRetroactiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trStopGapCheckboxRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trStopGapCheckboxRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkStopGap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStopGap As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trStopGapDataRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trStopGapDataRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblStopGapLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStopGapLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStopGapPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStopGapPayroll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddStopGapLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddStopGapLimit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtStopGapPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStopGapPayroll As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkContractorsEquipmentInstallation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContractorsEquipmentInstallation As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trContractorsRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContractorsRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlContractorsPropertyLimitAtEachCoveredJobsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlContractorsPropertyLimitAtEachCoveredJobsite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtContractorsToolsAndEquipmentBlanketLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractorsToolsAndEquipmentBlanketLimit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trContractorsToolsAndEquipmentSubLimitRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContractorsToolsAndEquipmentSubLimitRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlContractorsToolsAndEquipmentBlanketSubLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlContractorsToolsAndEquipmentBlanketSubLimit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtContractorsToolsAndEquipmentScheduledLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractorsToolsAndEquipmentScheduledLimit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContractorsRentedLeasedToolsAndEquipmentLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractorsRentedLeasedToolsAndEquipmentLimit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContractorsEmployeesToolsLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractorsEmployeesToolsLimit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkCrime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCrime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trCrimeRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCrimeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtCrimeNumberOfEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrimeNumberOfEmployees As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCrimeNumberOfLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrimeNumberOfLocations As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCrimeTotalLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCrimeTotalLimit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trForgeryAndAlterationsLimitRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trForgeryAndAlterationsLimitRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkForgeryAlterationOptionalLimits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkForgeryAlterationOptionalLimits As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEarthquake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEarthquake As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHiredAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHiredAuto As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkNonOwned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNonOwned As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trNonOwnedInfoRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNonOwnedInfoRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkElectronicData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkElectronicData As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trElectronicDataRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trElectronicDataRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtElectronicDataLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtElectronicDataLimit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trILContractorsHomeRepairAndRemodelingCheckboxRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trILContractorsHomeRepairAndRemodelingCheckboxRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkILContractorsHomeRepairAndRemodeling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkILContractorsHomeRepairAndRemodeling As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trILContractorsHomeRepairAndRemodelingDataRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trILContractorsHomeRepairAndRemodelingDataRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''hddAccord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddAccord As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlBasicButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBasicButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnSavePolicyLevelCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePolicyLevelCoverages As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocations As Global.System.Web.UI.WebControls.Button
End Class
