'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_BOP_ENDO_GeneralInformation

    '''<summary>
    '''divMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkBtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''trProgramTypeRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trProgramTypeRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlProgramType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProgramType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlOccurrenceLiabilityLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOccurrenceLiabilityLimit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTenantsFireLiability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTenantsFireLiability As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPropertyDamageLiabilityDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertyDamageLiabilityDeductible As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPropDmgLiabLimitPerClaimOrOccurrence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropDmgLiabLimitPerClaimOrOccurrence As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkBusinessMasterEnhancedEndorsement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBusinessMasterEnhancedEndorsement As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlBlanketRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBlanketRating As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hddAccord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddAccord As Global.System.Web.UI.WebControls.HiddenField
End Class
