'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VR3CAPQuote
    
    '''<summary>
    '''ctl_WorkflowManager_Quote_CAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_WorkflowManager_Quote_CAP As Global.IFM.VR.Web.ctl_WorkflowMgr_Quote_CAP
End Class
