services:
  # HTTPS Proxy (Nginx)
  nginx-proxy:
    image: nginx:alpine
    container_name: agentc-proxy
    ports:
      - "443:443"
      - "5173:5173"
    volumes:
      - ./config/nginx.conf.frontend-only:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
    networks:
      - agent-c-network
    restart: unless-stopped

  frontend:
    image: agentc-frontend:latest
    container_name: agentc-frontend
    expose:
      - "5173"
    environment:
      - PORT=5173
      - NEXT_PUBLIC_APP_URL=https://localhost:5173
      - AGENT_C_API_URL=http://host.docker.internal:8000
      - NEXT_PUBLIC_AGENTC_API_URL=wss://localhost:8000
    restart: unless-stopped
    networks:
      - agent-c-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agent-c-network:
    driver: bridge
