# PLANE API Configuration - VERIFIED
# Generated: 2025-10-15
# Status: Ready for Tool Development

plane:
  # PLANE Instance Configuration
  instance_url: "http://localhost"
  api_key: "plane_api_623e92aaced748629a60efcb603af928"
  
  # Workspace Configuration
  workspace_slug: "agent_c"
  workspace_id: "TBD"  # Will be populated after verification
  
  # API Configuration
  api_base: "/api"
  api_version: "v1"
  auth_header: "X-Api-Key"
  
  # Request Configuration
  timeout: 30  # seconds
  retry_attempts: 3
  retry_backoff: 2  # exponential backoff multiplier
  
  # Rate Limiting
  rate_limit: 100  # requests per minute
  rate_limit_window: 60  # seconds
  
  # Caching
  cache_enabled: true
  cache_ttl: 300  # seconds (5 minutes)
  
  # Response Configuration
  pagination_size: 50
  max_results: 1000
  
  # Logging
  log_level: "INFO"
  log_requests: true
  log_responses: false  # Set true for debugging

# User Information (from API)
user:
  id: "a209cdb3-724e-4fd5-b29d-6bb404c40d77"
  name: "Ethan Booth"
  email: "ethan.booth@centricconsulting.com"

# Verification Status
verification:
  api_connection: true
  authentication: true
  user_profile: true
  workspace_access: "pending"  # Run verify_workspace.py
  projects_access: "pending"
  verified_date: "2025-10-15"
