'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlDFROptionalCoverages
    
    '''<summary>
    '''dvOptionalCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvOptionalCoverages As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvCoverageContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCoverageContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvACV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvACV As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkACV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkACV As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblACV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblACV As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dvEarthquake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvEarthquake As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkEarthquake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEarthquake As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblEarthquake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEarthquake As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dvEarthquakeDeduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvEarthquakeDeduct As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlEarthquakeDeduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEarthquakeDeduct As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dvReplacment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvReplacment As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkReplacement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReplacement As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblReplacement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReplacement As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dvMineSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvMineSub As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dvMineSubA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvMineSubA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkMineSubA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMineSubA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblMineSubA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMineSubA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dvMineSubAB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvMineSubAB As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkMineSubAB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMineSubAB As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblMineSubAB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMineSubAB As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dvSinkhole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvSinkhole As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkSinkhole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSinkhole As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSinkhole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSinkhole As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dvOptionalButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvOptionalButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSaveOptionalCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveOptionalCoverages As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRateOptional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRateOptional As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dvEndorsementButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvEndorsementButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnMakeAChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMakeAChange As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnViewGotoNextSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewGotoNextSection As Global.System.Web.UI.WebControls.Button
End Class
