services:
  api:
    image: ghcr.io/centricconsulting/agent_c_api_dev:latest
    env_file:
      - ${AGENT_C_CONFIG_PATH}/agent_c.config
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ${AGENT_C_IMAGES_PATH}:/app/images  # Mounted volume for saved images
      - ${AGENT_C_PERSONAS_PATH}:/app/personas/local  # Mount personas directory - required for persona selection
      - ${DOCUMENTS_WORKSPACE}:/app/workspaces/documents  # Mount documents workspace directory
      - ${DOWNLOADS_WORKSPACE}:/app/workspaces/downloads  # Mount downloads workspace directory
      - ${DESKTOP_WORKSPACE}:/app/workspaces/desktop  # Mount desktop workspace directory
      - ${PROJECT_WORKSPACE_PATH}:/app/workspaces/project  # Mount point for projects
      - ${AGENT_C_LOGS_PATH}:/app/logs  # Mount logs directory
    environment:
      - ENVIRONMENT=LOCAL_DEV
      - ENHANCED_DEBUG_INFO=True
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=True
    networks:
      - agent-c-network

  frontend:
    image: ghcr.io/centricconsulting/agent_c_frontend_dev:latest
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1  # Use localhost for browser access
      - VITE_RAG_API_URL=http://localhost:8000/api/v1  # Use localhost for browser access
    depends_on:
      - api
    networks:
      - agent-c-network

networks:
  agent-c-network:
    driver: bridge
