services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    networks:
      - agent-c-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    image: ghcr.io/centricconsulting/agent_c_api_dev:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}  # Default to amd64 but allow override
    env_file:
      - ${AGENT_C_CONFIG_PATH}/agent_c.config
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ${AGENT_C_IMAGES_PATH}:/app/images  # Mounted volume for saved images
      - ${AGENT_C_PERSONAS_PATH}:/app/agent_c_config/agents/local  # Local agents
      - ${DOCUMENTS_WORKSPACE}:/app/workspaces/documents  # Mount documents workspace directory
      - ${DOWNLOADS_WORKSPACE}:/app/workspaces/downloads  # Mount downloads workspace directory
      - ${DESKTOP_WORKSPACE}:/app/workspaces/desktop  # Mount desktop workspace directory
      - ${PROJECT_WORKSPACE_PATH}:/app/workspaces/project  # Mount point for projects
      - ${AGENT_C_LOGS_PATH}:/app/logs  # Mount logs directory
    environment:
      - ENVIRONMENT=LOCAL_DEV
      - ENHANCED_DEBUG_INFO=True
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=True
    depends_on:
      - redis
    networks:
      - agent-c-network

  frontend:
    image: ghcr.io/centricconsulting/agent_c_frontend_dev:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}  # Default to amd64 but allow override
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1  # Use localhost for browser access
      - VITE_RAG_API_URL=http://localhost:8000/api/v1  # Use localhost for browser access
    depends_on:
      - api
      - redis
    networks:
      - agent-c-network

networks:
  agent-c-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
