services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    networks:
      - agent-c-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: dockerfiles/api.Dockerfile
    env_file:
      - ../.env
    ports:
      - "8800:8000"
    restart: always
    volumes:
      - ../src:/app/src  # For development hot-reloading
      - ../images:/app/images  # Mounted volume for saved images
      - ../personas:/app/personas  # Mount personas directory - required for persona selection
    environment:
      - ENVIRONMENT=LOCAL_DEV
      - ENHANCED_DEBUG_INFO=True
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=True
    depends_on:
      - redis
    networks:
      - agent-c-network

  frontend:
    build:
      context: ..
      dockerfile: dockerfiles/frontend.Dockerfile
    restart: always
    ports:
      - "5175:5173"
    #volumes:
    #  - ../src/agent_c_api_ui/agent_c_react_client:/app  # For development hot-reloading
    #  - /app/node_modules  # Keeps the container’s node_modules intact
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1  # Use localhost for browser access
      - VITE_RAG_API_URL=http://localhost:8001/api/v1  # Use localhost for browser access
    depends_on:
      - api
      - redis
    networks:
      - agent-c-network

networks:
  agent-c-network:
    driver: bridge

volumes:
  redis_data:
    driver: local