services:
  api:
    image: ghcr.io/centricconsulting/agent_c_api_dev:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}  # Default to amd64 but allow override
    env_file:
      - ${AGENT_C_CONFIG_PATH}/agent_c.config
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ${AGENT_C_IMAGES_PATH}:/app/images  # Mounted volume for saved images
      - ${AGENT_C_PERSONAS_PATH}:/app/agent_c_config/agents/local  # Local agents
      - ${DOCUMENTS_WORKSPACE}:/app/workspaces/documents  # Mount documents workspace directory
      - ${DOWNLOADS_WORKSPACE}:/app/workspaces/downloads  # Mount downloads workspace directory
      - ${DESKTOP_WORKSPACE}:/app/workspaces/desktop  # Mount desktop workspace directory
      - ${PROJECT_WORKSPACE_PATH}:/app/workspaces/project  # Mount point for projects
      - ${AGENT_C_SAVED_CHAT_FOLDER}:/app/agent_c_config/saved_sessions  # Mount shat session save folder.
    environment:
      - ENVIRONMENT=LOCAL_DEV
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=True
    networks:
      - agent-c-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentc-realtime-demo:latest
    container_name: agentc-realtime-demo
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - NEXT_PUBLIC_APP_URL=https://localhost:5173
      - AGENT_C_API_URL=https://localhost:8000
      - NEXT_PUBLIC_AGENTC_API_URL=wss://localhost:8000
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - agent-c-network
    # Healthcheck for the Next.js app
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:5173" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agent-c-network:
    driver: bridge
