'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlRV_WatercraftList

    '''<summary>
    '''dvRVWatercraftList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvRVWatercraftList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rvWaterRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvWaterRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''hiddenActiveRVWatercraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenActiveRVWatercraft As Global.System.Web.UI.WebControls.HiddenField
End Class
