'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlRV_Watercraft

    '''<summary>
    '''lblCommonRVWatercraftHdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommonRVWatercraftHdr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAdd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRemove As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divContents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlVehType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehType As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblVehType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVehType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVehType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divVehTypeoWatercraftText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divVehTypeoWatercraftText As Global.System.Web.UI.HtmlControls.HtmlGenericControl


    '''<summary>
    '''pnlVehicleInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehicleInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlCoverageOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCoverageOptions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCoverageOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoverageOptions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCoverageOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCoverageOptions As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCoverageOptionPDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoverageOptionPDL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCoverageOptionPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoverageOptionPD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCoverageOptionLib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoverageOptionLib As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPropertyDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPropertyDeductible As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPropertyDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPropertyDeductible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPropertyDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertyDeductible As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlPropertyDeductibleTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPropertyDeductibleTextBox As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPropertyDeductibleTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPropertyDeductibleTextBox As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPropertyDeductibleTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPropertyDeductibleTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlVehYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehYear As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblVehYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVehYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlVehLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehLength As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblVehLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehLength As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVehLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehLength As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlVehCostNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehCostNew As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblVehCostNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehCostNew As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVehCostNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehCostNew As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMotorType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMotorType As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMotorType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HiddenMotorButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenMotorButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlMotorType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMotorType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMotorTypeOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorTypeOut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMotorTypeIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorTypeIn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMotorTypeInOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorTypeInOut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlRVWLiabilityOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRVWLiabilityOnly As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRVWLiabilityOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRVWLiabilityOnly As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkRVWLiabilityOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRVWLiabilityOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlBodilyInjuryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBodilyInjuryLimit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBodilyInjuryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBodilyInjuryLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlBodilyInjuryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBodilyInjuryLimit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlUnder25Operator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUnder25Operator As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkUnder25Operator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnder25Operator As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUnder25Operator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnder25Operator As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUnder25OperMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnder25OperMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlVehSerialNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehSerialNum As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblVehSerialNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehSerialNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVehSerialNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehSerialNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlVehMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehMake As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblVehMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehMake As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVehMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehMake As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlVehModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVehModel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblVehModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehModel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVehModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehModel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlOwnerOtherThanInsured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOwnerOtherThanInsured As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkOwnerOtherThanInsured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOwnerOtherThanInsured As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlCollisionCoverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCollisionCoverage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkCollisionCoverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCollisionCoverage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDescription As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMaxChar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxChar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMaxCharCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxCharCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divMotorInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMotorInput As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''h3Motor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents h3Motor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkClearMotor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClearMotor As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSaveMotor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveMotor As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlHorsepowerCCs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHorsepowerCCs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblHorsepowerCCs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHorsepowerCCs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtHorsepowerCCs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHorsepowerCCs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMotorYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMotorYear As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMotorYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotorYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotorYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMotorCostNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMotorCostNew As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMotorCostNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorCostNew As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotorCostNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotorCostNew As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMotorSerialNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMotorSerialNum As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMotorSerialNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorSerialNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotorSerialNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotorSerialNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMotorMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMotorMake As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMotorMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorMake As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotorMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotorMake As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMotorModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMotorModel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMotorModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotorModel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotorModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotorModel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hiddenMotorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenMotorInfo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlRvWaterButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRvWaterButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnAddRVWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRVWater As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveRVWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveRVWater As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRateRVWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRateRVWater As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hiddenSelectedCoverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenSelectedCoverage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenPhysicalDamage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenPhysicalDamage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenSelectedForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenSelectedForm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenMotorType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenMotorType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenWatercraftType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenWatercraftType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenLOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenLOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenOccupancyCodeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenOccupancyCodeID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenIsEndorsementQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenIsEndorsementQuote As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenMaxCharCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenMaxCharCount As Global.System.Web.UI.WebControls.HiddenField
End Class
