'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_PF_ScheduledConstEquipment
    
    '''<summary>
    '''TitleQuoteNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleQuoteNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PolicyHolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyHolderName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DBANameElement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DBANameElement As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DBAName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DBAName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptSchedConEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSchedConEquip As Global.System.Web.UI.WebControls.Repeater
End Class
