'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlUWQuestionsPopup

    '''<summary>
    '''divUwQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUwQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdnIsHOMLossHistoryKillQuestionAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIsHOMLossHistoryKillQuestionAvailable As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnIsDFRLossHistoryKillQuestionAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIsDFRLossHistoryKillQuestionAvailable As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnRAPANewSymbolsEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRAPANewSymbolsEnabled As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnIsNewQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIsNewQuote As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnCopyQuoteEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCopyQuoteEffectiveDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''div_EffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_EffectiveDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUWQuestionsEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUWQuestionsEffectiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtUWQuestionsEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUWQuestionsEffectiveDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEffectiveDateError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEffectiveDateError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdditionalEffectiveDateError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdditionalEffectiveDateError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnOriginalEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnOriginalEffectiveDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppMinimumEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppMinimumEffectiveDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppMaximumEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppMaximumEffectiveDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppMinimumEffectiveDateAllQuotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppMinimumEffectiveDateAllQuotes As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppMaximumEffectiveDateAllQuotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppMaximumEffectiveDateAllQuotes As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppQuoteHasMinimumEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppQuoteHasMinimumEffectiveDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppMinimumQuoteEffectiveDateIsGreaterThanDateForAllQuotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppMinimumQuoteEffectiveDateIsGreaterThanDateForAllQuotes As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppBeforeDateMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppBeforeDateMsg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppAfterDateMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppAfterDateMsg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''divDwellingAgeDFR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDwellingAgeDFR As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''radDwellingAgeYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDwellingAgeYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radDwellingAgeNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDwellingAgeNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''divLossHistoryHOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLossHistoryHOM As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''radLossYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radLossYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radLossNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radLossNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Repeater1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divAddtionalAutoQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddtionalAutoQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''radMultiPolicyYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radMultiPolicyYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radMultiPolicyNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radMultiPolicyNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tr_ppa_8MoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ppa_8MoreInfo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtMoreInfoRelated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoreInfoRelated As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divAdditionalHomeQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdditionalHomeQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''radHOMMultiPolicyYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radHOMMultiPolicyYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radHOMMultiPolicyNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radHOMMultiPolicyNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tr_hom_MoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_hom_MoreInfo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtMoreInfoRelatedAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoreInfoRelatedAuto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divAdditionalDFRQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdditionalDFRQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''radDFRYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDFRYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radDFRNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDFRNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tr_dfr_MoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_dfr_MoreInfo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtMoreInfoDFR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoreInfoDFR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divAdditionalBOPQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdditionalBOPQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''radBOPCondoDandOYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPCondoDandOYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radBOPCondoDandONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPCondoDandONo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trBOPOver35k control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBOPOver35k As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''radBOPOver35kYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPOver35kYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radBOPOver35kNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPOver35kNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trBOPOver3Stories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBOPOver3Stories As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''radBOPOver3StoriesYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPOver3StoriesYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radBOPOver3StoriesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPOver3StoriesNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trBOPSales6M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBOPSales6M As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''radBOPSales6MYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPSales6MYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radBOPSales6MNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPSales6MNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radBOPIncOcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPIncOcc As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''radBOPIncOccYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPIncOccYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radBOPIncOccNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBOPIncOccNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tr_BOP_IncidentalOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_BOP_IncidentalOccupancy As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtIncidentalOccupancyRelated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncidentalOccupancyRelated As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divCommDataPrefill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCommDataPrefill As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CommDataPrefillTableRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommDataPrefillTableRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''radCommDataPrefillYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCommDataPrefillYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radCommDataPrefillNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCommDataPrefillNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''divFormType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFormType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddHomFormList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddHomFormList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divFarmDogQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFarmDogQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rad_far_Dog14Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rad_far_Dog14Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rad_far_Dog14No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rad_far_Dog14No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtFar_How_Many_Dogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFar_How_Many_Dogs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rad_far_Dog14bYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rad_far_Dog14bYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rad_far_Dog14bNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rad_far_Dog14bNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tr_far_Dog14bYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_far_Dog14bYes As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_far_Dog14bMoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_far_Dog14bMoreInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divUmbrellaSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUmbrellaSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UmbrellaTypePersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaTypePersonal As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UmbrellaTypeFarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaTypeFarm As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UmbrellaFarmTypePersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaFarmTypePersonal As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UmbrellaFarmTypeCommercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaFarmTypeCommercial As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UmbrellaFarmCommercialTypeIndividual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaFarmCommercialTypeIndividual As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UmbrellaFarmCommercialTypeFamilyPartnership control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaFarmCommercialTypeFamilyPartnership As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UmbrellaFarmSizeSmall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaFarmSizeSmall As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UmbrellaFarmSizeLarge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UmbrellaFarmSizeLarge As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Tr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''GoverningStateSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoverningStateSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlGoverningState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGoverningState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hiddenSelectedForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenSelectedForm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnShowDatePickerOnPageLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnShowDatePickerOnPageLoad As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
