'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlFarmIncidentalLimits

    '''<summary>
    '''dvPersPropList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPersPropList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblPersPropHdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPersPropHdr As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblPropCoverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPropCoverage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLimits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLimits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPropLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPropLimit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPropPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPropPrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblFarmIncidentalLimits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFarmIncidentalLimits As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tblTotalPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTotalPrem As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblTotalPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalPremData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPremData As Global.System.Web.UI.WebControls.Label
End Class
