using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IFM.DataServicesCore.CommonObjects.Fiserv
{
    [System.Serializable]
    public class WalletItem // : ModelBase
    {
        public int FiservWalletItemId { get; set; } //generated by IFM after Create
        public string Nickname { get; set; } //required; Create and Update
        public string FundingAccountToken { get; set; } //generated by Fiserv (their key)
        public string FundingMethod { get; set; } //ACH, ACCEL, STAR, VISA, DISCOVER, etc.; not set on Create or Update; should come back from Fiserv
        public string FundingCategory { get; set; } //Check, Debit, Credit; not set on Create or Update; should come back from Fiserv
        public string FundingAccountLastFourDigits { get; set; } //not set on Create or Update; should come back from Fiserv
        public string FundingAccountType { get; set; } //Personal, Business; for Bank info; Create and Update
        public string BankAccountType { get; set; } //Checking, Saving; for Bank info; Create and Update
        public string ExpirationMonth { get; set; } //won't ever come back but used for Update; for Card info; would also be used for Create if we're supporting wallet functionality but not using Fiserv's iframe
        public string ExpirationYear { get; set; } //won't ever come back but used for Update; for Card info; would also be used for Create if we're supporting wallet functionality but not using Fiserv's iframe
        public string ZipCode { get; set; } //won't ever come back but used for Update; for Card info
        public string CreditCardNumber { get; set; } //won't ever come back; would only be used if we're supporting wallet functionality but not using Fiserv's iframe; for Create only; cannot be updated
        public string SecurityCode { get; set; } //won't ever come back; would only be used if we're supporting wallet functionality but not using Fiserv's iframe; for Create only; cannot be updated
        public string FirstName { get; set; } //for Bank info; Create and Update
        public string LastName { get; set; } //for Bank info; Create and Update
        public string RoutingNumber { get; set; } //won't ever come back; for Bank info; for Create only; cannot be updated
        public string CheckAccountNumber { get; set; } //won't ever come back; for Bank info; for Create only; cannot be updated
        public string BankName { get; set; } //for Bank info; not set on Create or Update; may come back from Fiserv
        public string KeyIdentifier { get; set; } //Fiserv.Session.UserId
        public int FiservWalletId { get; set; } //generated by IFM at Wallet Creation
        public string EmailAddress { get; set; } //would only be set at Create; will be used for Wallet EmailAddress if it's the 1st WalletItem in the Wallet; can only be updated from Wallet
        public List<string> ActiveRccPolicies { get; set; } //will contain the policy #s for any active RCC accounts tied to the walletItem; cannot delete the walletItem if any policies are tied to it
        public List<string> ActiveAndUnprocessedScheduledPaymentPolicies { get; set; } //will contain the policy #s for any active unprocessed scheduled payments tied to the walletItem; cannot delete the walletItem if any policies are tied to it
        public string EncryptedRoutingNumber { get; set; } //added 5/4/2023; only needed when UI code returns Wallets/WalletItems
        public string EncryptedCheckAccountNumber { get; set; } //added 5/4/2023; only needed when UI code returns Wallets/WalletItems
    }

    //added 6/29/2020
    [System.Serializable]
    public class AddWalletItemBody // : ModelBase
    {
        public WalletItem Item { get; set; }
        public IFM_CreditCardProcessing.Enums.UserType UserType { get; set; }
        public string UserName { get; set; }
        public string Fiserv_AuthToken { get; set; } //obtained for use w/ iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public string Fiserv_SessionToken { get; set; } //obtained for use w/ iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public int Fiserv_SessionId { get; set; } //obtained while getting tokens used w/ iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public string Fiserv_FundingAccountToken { get; set; } //obtained from iframe; not required if not using iframe; would only be used for Card payments (not Bank)
        public bool IsFromOneView { get; set; } //should be set to True for service calls coming from OneView (likely won't update this info from there)
    }


    //added 6/30/2020
    [System.Serializable]
    public class UpdateWalletItemBody // : ModelBase
    {
        public WalletItem Item { get; set; }
        public IFM_CreditCardProcessing.Enums.UserType UserType { get; set; }
        public string UserName { get; set; }
        public bool IsFromOneView { get; set; } //should be set to True for service calls coming from OneView (likely won't update this info from there)
    }


    [System.Serializable]
    public class DeleteWalletItemBody // : ModelBase
    {
        public WalletItem Item { get; set; }
        public IFM_CreditCardProcessing.Enums.UserType UserType { get; set; }
        public string UserName { get; set; }
        public bool IsFromOneView { get; set; } //should be set to True for service calls coming from OneView (likely won't update this info from there)
    }



}
