using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IFM.DataServicesCore.CommonObjects.Fiserv
{
    [System.Serializable]
    public class Wallet : ModelBase //not specific Create method; automatically created whenever the 1st WalletItem is created
    {
        public int FiservWalletId { get; set; }  //generated by IFM after Create
        public string ConsumerName { get; set; } //can be updated; may not use
        public string ConsumerEmail { get; set; } //can be updated; will be initially set based on emailAddress for 1st WalletItem
        public string ConsumerPhone { get; set; } //can be updated; may not use
        public string KeyIdentifier { get; set; } //Fiserv.Session.UserId
        public List<WalletItem> Items { get; set; } //can have multiple WalletItems tied to a Wallet; cannot update WalletItems via UpdateWallet method
    }


    //added 7/30/2020
    [System.Serializable]
    public class UpdateWalletBody : ModelBase
    {
        public Wallet Item { get; set; }
        public IFM_CreditCardProcessing.Enums.UserType UserType { get; set; }
        public string UserName { get; set; }
        public bool IsFromOneView { get; set; } //should be set to True for service calls coming from OneView (likely won't update this info from there)

        public UpdateWalletBody()
        {

        }

        public UpdateWalletBody(UpdateWalletsBody walletsBody, Wallet walletItem)
        {
            this.Item = walletItem;
            this.UserType = walletsBody.UserType;
            this.IsFromOneView = walletsBody.IsFromOneView;
            this.UserName = walletsBody.UserName;
        }
    }

    [System.Serializable]
    public class UpdateWalletsBody : ModelBase
    {
        public List<Wallet> Items { get; set; }
        public IFM_CreditCardProcessing.Enums.UserType UserType { get; set; }
        public string UserName { get; set; }
        public bool IsFromOneView { get; set; } //should be set to True for service calls coming from OneView (likely won't update this info from there)
    }


}
