'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_FUPPUP_UnderlyingPolicy_Item

    '''<summary>
    '''divUmbrellaUnderlyingPolicyItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUmbrellaUnderlyingPolicyItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLobCategoryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLobCategoryText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptPolicyList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPolicyList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblLobCategoryMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLobCategoryMsg As Global.System.Web.UI.WebControls.Label
End Class
