'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_CPP_InlandMarine

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClear As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cov_ContractorIMEndorsement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_ContractorIMEndorsement As Global.IFM.VR.Web.cov_ContractorEndorsement

    '''<summary>
    '''cov_BuildersRisk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_BuildersRisk As Global.IFM.VR.Web.cov_BuildersRisk

    '''<summary>
    '''cov_Computer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_Computer As Global.IFM.VR.Web.cov_Computer

    '''<summary>
    '''cov_Contractor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_Contractor As Global.IFM.VR.Web.cov_Contractor

    '''<summary>
    '''cov_FineArtsFloater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_FineArtsFloater As Global.IFM.VR.Web.cov_FineArtsFloater

    '''<summary>
    '''cov_InstallationFloater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_InstallationFloater As Global.IFM.VR.Web.cov_InstallationFloater

    '''<summary>
    '''cov_MotorTruckCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_MotorTruckCargo As Global.IFM.VR.Web.cov_MotorTruckCargo

    '''<summary>
    '''cov_OwnersCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_OwnersCargo As Global.IFM.VR.Web.cov_OwnersCargo

    '''<summary>
    '''cov_ScheduledPropertyFloater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_ScheduledPropertyFloater As Global.IFM.VR.Web.cov_ScheduledPropertyFloater

    '''<summary>
    '''cov_Signs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_Signs As Global.IFM.VR.Web.cov_Signs

    '''<summary>
    '''cov_Transportation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cov_Transportation As Global.IFM.VR.Web.cov_Transportation

    '''<summary>
    '''ctl_AdditionalInterestList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AdditionalInterestList As Global.IFM.VR.Web.ctlVehicleAdditionalInterestList

    '''<summary>
    '''ctl_AdditionalInterest_MiniSerach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AdditionalInterest_MiniSerach As Global.IFM.VR.Web.ctl_AdditionalInterest_MiniSerach

    '''<summary>
    '''ctl_IM_AssignedAIList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_IM_AssignedAIList As Global.IFM.VR.Web.ctl_InlandMarineAssignedAIList

    '''<summary>
    '''divActionButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divActionButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnToCrime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToCrime As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEmailForUWAssistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmailForUWAssistance As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''divEndorsementButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEndorsementButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnMakeAChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMakeAChange As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewCrime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewCrime As Global.System.Web.UI.WebControls.Button
End Class
