'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_Vehicle_App

    '''<summary>
    '''lblAccordHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccordHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkBtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtVinNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVinNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divConfirmResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConfirmResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ctlVehicleAdditionalInterestList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlVehicleAdditionalInterestList As Global.IFM.VR.Web.ctlVehicleAdditionalInterestList

    '''<summary>
    '''ctlCoverage_PPA_ScheduledItemsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCoverage_PPA_ScheduledItemsList As Global.IFM.VR.Web.ctlCoverage_PPA_ScheduledItemsList

    '''<summary>
    '''divNoContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNoContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNoContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoContent As Global.System.Web.UI.WebControls.Label
End Class
