Public Class Enums

    ' Added 6/30/15 MGB for FNOL Rewrite
    Enum FNOL_LOB_Enum
        Auto
        CommercialAuto
        Liability
        Propertty
    End Enum

    Enum UserCategoryID
        Employee = 1
        Client = 2
        Agency = 3
    End Enum

    Enum ClaimFaultType
        NA = 0
        AtFault = 1
        ComparativeFaultInsdlessthan50percent = 2
        ComparativeFaultInsd50percentormore = 3
        NotAtFault = 4
        Undetermined = 5
    End Enum

    ' Added 12/8/2020 MGB
    Enum ClaimSeverity_Id
        Fatality = 7
        MinorInjury = 4
        MinorLoss = 1
        ModerateInjury = 5
        ModerateLoss = 2
        SevereInjury = 6
        SevereLoss = 3
    End Enum

    ' Added 6/30/15 MGB for FNOL Rewrite
    Enum ClaimLossType_Auto
        SingleVehicleAccident = 194 'PPA, CAP, GAR
        MultiVehicleAccident = 193 'PPA, CAP, GAR
        Fire = 199 'PPA, CAP, GAR; 37 for BOP, CIM, CPR, DFR, FAR, HOM, PIM
        TheftPartsAndContent = 206 'PPA, CAP, GAR
        TheftTotalVehicle = 207 'PPA, CAP, GAR
        VandalismAndMischief = 209 'PPA, CAP, GAR
        GlassReplace = 202 'PPA, CAP, GAR
        GlassRepair = 201 'PPA, CAP, GAR
        Wind = 210 'PPA, CAP, GAR
        Hail = 203 'PPA, CAP, GAR; 39 for BOP, CIM, CPR, DFR, FAR, HOM
        Earthquake = 196 'PPA, CAP, GAR; 63 for BOP, CIM, CPR, DFR, FAR, HOM
        RiotOrCivilCommotion = 205 'PPA, CAP, GAR; 183 for BOP, CIM, CPR, DFR, FAR, HOM
        TowingAndLabor = 208 'PPA, CAP, GAR
        AnimalCollision = 195 'PPA, CAP, GAR
        OtherNOC = 211 'PPA, CAP, GAR; 178 for DFR, FAR, HOM, PIM; 251 for BOP, CRM, CIM, CPR
        Explosion = 197 'PPA, CAP, GAR
        EnvironmentalSpill = 136 'PPA, CAP, GAR
        Flood = 200 'PPA, CAP, GAR
        Water = 204 'PPA, CAP, GAR
        FallingObjectsOrMissiles = 198 'PPA, CAP, GAR
        NonMovingVehicle = 212 'PPA, CAP, GAR
    End Enum

    ' Added 6/30/15 MGB for FNOL Rewrite
    Enum ClaimLossType_Property
        Fire = 37 'BOP, CIM, CPR, DFR, FAR, HOM, PIM; 199 for PPA, CAP, GAR
        WindOrTornado = 38 'BOP, CIM, CPR, DFR, FAR, HOM
        Hail = 39 'BOP, CIM, CPR, DFR, FAR, HOM; 203 for PPA, CAP, GAR
        Smoke = 40 'BOP, CIM, CPR, DFR, FAR, HOM
        BackupOfSewerOrDrain = 41 'BOP, CIM, CPR, DFR, FAR, HOM
        Collapse = 247 'BOP, CIM, CPR; 42 for DFR, FAR, HOM
        Environmental = 46 'BOP, CIM, CPR, DFR, FAR, HOM
        EquipmentBreakdown = 166 'CIM, CPR, DFR, FAR, HOM
        Explosion = 167 'BOP, CIM, CPR, DFR, FAR, HOM
        Theft = 49 'BOP, CRM, CIM, CPR, DFR, FAR, HOM, PIM
        GlassBreakage = 168 'CIM, CPR, DFR, FAR, HOM
        Lightning = 53 'BOP, CIM, CPR, DFR, FAR, HOM
        MineSubsidence = 175 'CIM, CPR, DFR, FAR, HOM
        OtherNOC = 251 'BOP, CRM, CIM, CPR; 178 for DFR, FAR, HOM, PIM; 211 for PPA, CAP, GAR
        PowerInterruption = 179 'CIM, CPR, DFR, FAR, HOM
        VandalismAndMaliciousMischief = 59 'BOP, CIM, CPR, DFR, FAR, HOM
        VehicleDamage = 176 'BOP, CIM, CPR, DFR, FAR, HOM
        WaterDamageOther = 177 'BOP, CIM, CPR, DFR, FAR, HOM
        WaterDamageAppliance = 180 'BOP, CIM, CPR, DFR, FAR, HOM
        WaterDamageWindDriven = 181 'BOP, CIM, CPR, DFR, FAR, HOM
        Landslide = 62 'BOP, CIM, CPR, DFR, FAR, HOM
        Earthquake = 63 'BOP, CIM, CPR, DFR, FAR, HOM; 196 for PPA, CAP, GAR
        Sinkhole = 64 'BOP, CIM, CPR, DFR, FAR, HOM
        AnimalDamage = 254 'BOP, CIM, CPR; 165 for DFR, FAR, HOM, PIM
        FalseAlarm = 261 'BOP, CIM, CPR; 66 for DFR, FAR, HOM
        MysteriousDisappearance = 67 'BOP, CIM, CPR, DFR, FAR, HOM, PIM
        Freezing = 182 'BOP, CIM, CPR, DFR, FAR, HOM
        RiotOrCivilCommotion = 183 'BOP, CIM, CPR, DFR, FAR, HOM; 205 for PPA, CAP, GAR
        Aircraft = 184 'BOP, CIM, CPR, DFR, FAR, HOM
        FallingObjects = 255 'BOP, CIM, CPR; 185 for DFR, FAR, HOM
        WeightOfIceSnowOrSleet = 256 'BOP, CIM, CPR; 186 for DFR, FAR, HOM
        DebrisRemoval = 257 'BOP, CIM, CPR; 187 for DFR, FAR, HOM
        CollisionUpsetOrOverturn = 213 'CIM, CPR, FAR, PIM
        FloodMachineryAndImplements = 214 'BOP, CIM, CPR, FAR, PIM
        LivestockCollision = 217 'BOP, CPR, FAR
        LivestockOther = 216 'BOP, CPR, FAR
        RoadbedCollision = 219 'CPR, FAR
    End Enum

    ' Added 6/30/15 MGB for FNOL Rewrite
    Enum ClaimLossType_Liability
        Fire = 37 'BOP, CIM, CPR, DFR, FAR, HOM, PIM; 199 for PPA, CAP, GAR
        WindOrTornado = 38 'BOP, CIM, CPR, DFR, FAR, HOM
        Hail = 39 'BOP, CIM, CPR, DFR, FAR, HOM; 203 for PPA, CAP, GAR
        Smoke = 40 'BOP, CIM, CPR, DFR, FAR, HOM
        BackupOfSewerOrDrain = 41 'BOP, CIM, CPR, DFR, FAR, HOM
        Collapse = 42 'DFR, FAR, HOM; 247 for BOP, CIM, CPR
        Environmental = 46 'BOP, CIM, CPR, DFR, FAR, HOM
        EquipmentBreakdown = 166 'CIM, CPR, DFR, FAR, HOM
        Explosion = 167 'BOP, CIM, CPR, DFR, FAR, HOM
        Theft = 49 'BOP, CRM, CIM, CPR, DFR, FAR, HOM, PIM
        GlassBreakage = 168 'CIM, CPR, DFR, FAR, HOM
        IdentityTheft = 169 'DFR, FAR, HOM
        Lightning = 53 'BOP, CIM, CPR, DFR, FAR, HOM
        MineSubsidence = 175 'CIM, CPR, DFR, FAR, HOM
        OtherNOC = 178 'DFR, FAR, HOM, PIM; 251 for BOP, CRM, CIM, CPR; 211 for PPA, CAP, GAR
        PowerInterruption = 179 'CIM, CPR, DFR, FAR, HOM
        VandalismAndMaliciousMischief = 59 'BOP, CIM, CPR, DFR, FAR, HOM
        VehicleDamage = 176 'BOP, CIM, CPR, DFR, FAR, HOM
        WaterDamageOther = 177 'BOP, CIM, CPR, DFR, FAR, HOM
        WaterDamageAppliance = 180 'BOP, CIM, CPR, DFR, FAR, HOM
        WaterDamageWindDriven = 181 'BOP, CIM, CPR, DFR, FAR, HOM
        Landslide = 62 'BOP, CIM, CPR, DFR, FAR, HOM
        Earthquake = 63 'BOP, CIM, CPR, DFR, FAR, HOM; 196 for PPA, CAP, GAR
        Sinkhole = 64 'BOP, CIM, CPR, DFR, FAR, HOM
        AnimalDamage = 165 'DFR, FAR, HOM, PIM; 254 for BOP, CIM, CPR
        FalseAlarm = 66 'DFR, FAR, HOM; 261 for BOP, CIM, CPR
        MysteriousDisappearance = 67 'BOP, CIM, CPR, DFR, FAR, HOM, PIM
        Freezing = 182 'BOP, CIM, CPR, DFR, FAR, HOM
        RiotOrCivilCommotion = 183 'BOP, CIM, CPR, DFR, FAR, HOM; 205 for PPA, CAP, GAR
        Aircraft = 184 'BOP, CIM, CPR, DFR, FAR, HOM
        FallingObjects = 185 'DFR, FAR, HOM; 255 for BOP, CIM, CPR
        WeightOfIceSnowOrSleet = 186 'DFR, FAR, HOM; 256 for BOP, CIM, CPR
        DebrisRemoval = 187 'DFR, FAR, HOM; 257 for BOP, CIM, CPR
        LiabilityPetBite = 171 'GAR, DFR, FAR, HOM
        LiabilitySlipAndFall = 174 'BOP, CGL, DFR, FAR, HOM
        LiabilityBusinessPursuits = 73 'DFR, FAR, HOM
        LiabilityMiscVehicle = 188 'BOP, CGL, DFR, FAR, HOM
        LiabilityEnvironmental = 172 'BOP, GAR, CGL, DFR, FAR, HOM
        LiabilityAnimalAndLivestock = 170 'BOP, GAR, CGL, DFR, FAR, HOM
        LiabilityNOC = 189 'BOP, GAR, CGL, DFR, FAR, HOM
        LiabilityWatercraft = 150 'BOP, GAR, CGL, DFR, FAR, HOM
        LiabilityTrampoline = 190 'DFR, FAR, HOM
        LiabilityServingOfAlcohol = 191 'BOP, GAR, CGL, DFR, FAR, HOM
        LiabilityDamageToPropertyOfOthers = 173 'GAR, CGL, DFR, FAR, HOM
        LiabilityPersonalInjury = 192 'GAR, DFR, FAR, HOM
    End Enum

    Enum ClaimLossType
        AccidentalDischargeOrLeakage = 87 'not used in Diamond
        AircraftDamage = 144 'not used in Diamond
        AllOther = 88 'not used in Diamond
        AllOtherPhysicalDamage = 89 'not used in Diamond
        Alteration = 157 'not used in Diamond
        AnimalDamage = 65 'not used in Diamond; use 165 or 254
        ApplianceRelatedWaterDamage = 90 'not used in Diamond
        BackupOfSewerOrDrain = 41
        BodilyInjuryAutoBI = 152 'not used in Diamond
        BroadFormPerilsAutoPAPDOrOTC = 86 'not used in Diamond
        Collapse = 42
        CollisionMultipleAutos = 113 'not used in Diamond
        CollisionOther = 114 'not used in Diamond
        CollisionSingleAuto = 115 'not used in Diamond
        CollisionUpsetOverturn = 91 'not used in Diamond
        ComprehensiveAnimal = 116 'not used in Diamond
        ComprehensiveEarthquake = 117 'not used in Diamond
        ComprehensiveExplosion = 118 'not used in Diamond
        ComprehensiveFallingObjectsOrMissiles = 119 'not used in Diamond
        ComprehensiveFire = 120 'not used in Diamond
        ComprehensiveFlood = 121 'not used in Diamond
        ComprehensiveGlassRepair = 122 'not used in Diamond
        ComprehensiveGlassReplace = 123 'not used in Diamond
        ComprehensiveHail = 124 'not used in Diamond
        ComprehensiveLabor = 125 'not used in Diamond
        ComprehensiveOther = 126 'not used in Diamond
        ComprehensiveOtherTransportation = 127 'not used in Diamond
        ComprehensiveOtherWater = 128 'not used in Diamond
        ComprehensiveRiotOrCivilCommotion = 129 'not used in Diamond
        ComprehensiveTheftPartial = 130 'not used in Diamond
        ComprehensiveTheftTotal = 131 'not used in Diamond
        ComprehensiveTowing = 132 'not used in Diamond
        ComprehensiveVandalismAndMischief = 133 'not used in Diamond
        ComprehensiveWind = 134 'not used in Diamond
        ComputerFraud = 161 'not used in Diamond
        Contamination = 143 'not used in Diamond
        ContaminationPollution = 92 'not used in Diamond
        Conversion = 162
        CreditCard = 93 'not used in Diamond
        DamageToPropertyOfOthers = 94 'not used in Diamond
        DeathAndDisabilityOrFuneral = 135 'not used in Diamond
        DestructionOfDataOrPrograms = 164 'not used in Diamond
        DogBiteLiability = 95 'not used in Diamond
        EarthMovement = 96 'not used in Diamond
        Earthquake = 63
        EmployeeTheft = 160 'not used in Diamond
        EnvironmentalSpill = 136
        EnvironmentalMiscellaneous = 46 'just Environmental in Diamond
        EnvironmentalMold = 44 'not used in Diamond
        EnvironmentalOther = 43 'not used in Diamond
        EnvironmentalPetroleum = 45 'not used in Diamond
        EquipmentBreakdown = 47 'not used in Diamond; use 166 or 248
        Explosion = 48 'not used in Diamond; use 167 or 197
        ExtendedCoveragePerils = 97 'not used in Diamond
        FalseAlarm = 66
        Fire = 37
        FireAutoPAPDOrOTC = 84 'not used in Diamond
        Flood = 98 'not used in Diamond; use 200
        Forgery = 142
        ForgeryOrAlteration = 158 'not used in Diamond
        FreezingWaterAndSubsequentWater = 99 'not used in Diamond
        GlassBreakage = 50 'not used in Diamond; use 168 or 249
        Hail = 39
        IdentityTheft = 51 'not used in Diamond; use 169
        InlandMarine = 52 'not used in Diamond
        IntakeofForeignObject = 100 'not used in Diamond; use 215 (IntakeOfForeignObjects)
        Landslide = 62
        LiabilityAllOther = 101 'not used in Diamond
        LiabilityAbuseOrMolestation = 147 'not used in Diamond
        LiabilityAdvertising = 153
        LiabilityAnimalOrLivestock = 81 'not used in Diamond; use 170
        LiabilityBodilyInjury = 69 'not used in Diamond
        LiabilityBusinessPursuits = 73
        LiabilityCollision = 74 'not used in Diamond
        LiabilityDogBite = 71 'not used in Diamond; use LiabilityPetBite (171 or 239)
        LiabilityEnvironmental = 75 'not used in Diamond; use 172
        LiabilityEnvironmentalMiscellaneous = 79 'not used in Diamond
        LiabilityEnvironmentalMold = 76 'not used in Diamond
        LiabilityEnvironmentalPetroleum = 77 'not used in Diamond
        LiabilityEnvironmentalSolidWaste = 78 'not used in Diamond
        LiabilityErrorsOrOmissions = 148 'not used in Diamond
        LiabilityGlass = 80 'not used in Diamond
        LiabilityMedPay = 68 'not used in Diamond
        LiabilityMiscellaneous = 82 'not used in Diamond
        LiabilityOtherAnimal = 154 'not used in Diamond
        LiabilityOverspray = 149 'not used in Diamond
        LiabilityOwnersProtectiveLiability = 155 'not used in Diamond
        LiabilityPersonal = 156 'not used in Diamond
        LiabilityPersonalTheft = 83 'not used in Diamond
        LiabilityPropertyDamage = 70 'not used in Diamond
        LiabilitySlipandFall = 72 'not used in Diamond; use 174
        LiabilityWatercraft = 150
        Lightning = 53
        Livestock = 102 'not used in Diamond
        LossAdjustmentExpense = 103 'not used in Diamond
        MedicalPayments = 104 'not used in Diamond
        MineSubsidence = 54 'not used in Diamond; use 175 or 250
        Miscellaneous = 55 'not used in Diamond
        Mold = 105 'not used in Diamond
        MysteriousDisappearance = 67
        MysteriousDisappearanceInvolvingScheduledProperty = 106 'not used in Diamond
        NotAvailable = 0
        PowerInterruptionOffPremise = 58 'not used in Diamond
        PowerInterruptionOnPremise = 57 'not used in Diamond
        RiotOrCivilCommotion = 145 'not used in Diamond; use 183 or 205
        Sinkhole = 64
        SlipOrFallLiability = 107 'not used in Diamond
        Smoke = 40
        SprinklerLeakage = 146 'not used in Diamond
        Suffocation = 151 'not used in Diamond
        TheftOther = 49 'just Theft in Diamond
        TheftofMoney = 56 'not used in Diamond
        TheftofMoneyandSecurities = 159 'not used in Diamond
        TheftInvolvingScheduledProperty = 108 'not used in Diamond
        TheftAutoPAPDOrOTC = 85 'not used in Diamond
        TheftOrBurglary = 109 'not used in Diamond
        UnauthorizedReproduction = 163 'not used in Diamond
        UninsuredMotoristBodilyInjury = 137 'not used in Diamond
        UninsuredMotoristPropertyDamage = 138 'not used in Diamond
        VandalismandMaliciousMischief = 59
        VehicleDamage = 60 'not used in Diamond; use 176
        WaterDamage = 61 'not used in Diamond; could use WaterDamageOther (177)
        Watercraft = 110 'not used in Diamond
        WeatherRelatedWaterDamage = 111 'not used in Diamond; could use WaterDamageWindDriven (181)
        WindOrTornado = 38
        WorkersCompensation = 112 'not used in Diamond; use 218 or 231, also WorkComp (232)

        'updated 8/3/2017 w/ missing values
        Aircraft = 184
        AnimalCollision = 195
        AnimalDamage2 = 165
        AnimalDamage3 = 254
        'BackupOfSewerOrDrain = 41
        BOP = 229
        Burglary = 245
        CGL = 230
        'Collapse = 42
        Collapse2 = 247
        CollisionUpsetOrOverturn = 213
        CollisionUpsetOrOverturn2 = 258
        CommercialAuto = 227
        CommercialGarage = 228
        'Conversion = 162
        DebrisRemoval = 187
        DebrisRemoval2 = 257
        DwellingFire = 225
        'Earthquake = 63
        Earthquake2 = 196
        EmployeeDishonesty = 246
        EmployersLiability = 221
        EmployersLiability2 = 233
        Environmental = 46
        'EnvironmentalSpill = 136
        EquipmentBreakdown2 = 166
        EquipmentBreakdown3 = 248
        Explosion2 = 167
        Explosion3 = 197
        FallingObjects = 185
        FallingObjects2 = 255
        FallingObjectsOrMissiles = 198
        'FalseAlarm = 66
        FalseAlarm2 = 261
        FamilyMedical = 220
        Farmowners = 226
        'Fire = 37
        Fire2 = 199
        Flood2 = 200
        FloodMachineryAndImplements = 214
        'Forgery = 142
        Freezing = 182
        GarageKeepersLiability = 235
        GlassBreakage2 = 168
        GlassBreakage3 = 249
        GlassRepair = 201
        GlassReplace = 202
        'Hail = 39
        Hail2 = 203
        Homeowners = 224
        IdentityTheft2 = 169
        IntakeOfForeignObjects = 215
        'Landslide = 62
        'LiabilityAdvertising = 153
        LiabilityAnimalOrLivestock2 = 170
        'LiabilityBusinessPursuits = 73
        LiabilityCompletedOps = 241
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityDamageToPropertyOfOthers2 = 260
        LiabilityEnvironmental2 = 172
        LiabilityFallingObjects = 243
        LiabilityIntellectualProperty = 238
        LiabilityLoadingOrUnloading = 236
        LiabilityMiscVehicle = 188
        LiabilityNOC = 189
        LiabilityPersonalInjury = 192
        LiabilityPersonalInjury2 = 242
        LiabilityPetBite = 171
        LiabilityPetBite2 = 239
        LiabilityProducts = 240
        LiabilityProductsOrCompletedOps = 237
        LiabilityServingOfAlcohol = 191
        LiabilitySlipAndFall2 = 174
        LiabilityTrampoline = 190
        'LiabilityWatercraft = 150
        'Lightning = 53
        LivestockOther = 216
        LivestockCollision = 217
        LoadingOrUnloading = 234
        LostStone = 222
        MineSubsidence2 = 175
        MineSubsidence3 = 250
        MultiVehicleAccident = 193
        'MysteriousDisappearance = 67
        NonMovingVehicle = 212
        OtherNOC = 178
        OtherNOC2 = 211
        OtherNOC3 = 251
        PersonalAuto = 223
        PowerInterruption = 179
        PowerInterruption2 = 252
        RiotOrCivilCommotion2 = 183
        RiotOrCivilCommotion3 = 205
        RoadbedCollision = 219
        RoadbedCollision2 = 259
        Robbery = 244
        SingleVehicleAccident = 194
        'Sinkhole = 64
        'Smoke = 40
        Theft = 49
        TheftPartsOrContents = 206
        TheftTotalVehicle = 207
        TowingAndLabor = 208
        UnderinsuredMotorist = 262
        VandalismAndMischief = 209
        'VandalismAndMaliciousMischief = 59
        VehicleDamage2 = 176
        Water = 204
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        WeightOfIceSnowOrSleet = 186
        WeightOfIceSnowOrSleet2 = 256
        Wind = 210
        'WindOrTornado = 38
        WorkComp = 232
        WorkersCompensation2 = 218
        WorkersCompensation3 = 231
    End Enum

    'added 7/29/2017
    Enum FNOL_Type
        AutoFNOL = 1
        LiabilityFNOL = 2
        PropertyFNOL = 3
    End Enum
    Enum ClaimLossType_PPA 'Auto Personal; same values as ClaimLossType_Auto
        AnimalCollision = 195 'ClaimLossType_Auto
        Earthquake = 196 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (63), ClaimLossType_Liability (63), and ClaimLossType (63)
        EnvironmentalSpill = 136 'ClaimLossType_Auto, ClaimLossType
        Explosion = 197 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (167), ClaimLossType_Liability (167), and ClaimLossType (48 - not used in Diamond)
        FallingObjectsOrMissiles = 198 'ClaimLossType_Auto
        Fire = 199 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (37), ClaimLossType_Liability (37), and ClaimLossType (37)
        Flood = 200 'ClaimLossType_Auto; same text but diff value in ClaimLossType (98 - not used in Diamond)
        GlassRepair = 201 'ClaimLossType_Auto
        GlassReplace = 202 'ClaimLossType_Auto
        Hail = 203 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (39), ClaimLossType_Liability (39), and ClaimLossType (39)
        MultiVehicleAccident = 193 'ClaimLossType_Auto
        NonMovingVehicle = 212 'ClaimLossType_Auto
        OtherNOC = 211 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (251) and ClaimLossType_Liability (178)
        RiotOrCivilCommotion = 205 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (183), ClaimLossType_Liability (183), and ClaimLossType (145 - not used in Diamond)
        SingleVehicleAccident = 194 'ClaimLossType_Auto
        TheftPartsOrContents = 206 'ClaimLossType_Auto:TheftPartsAndContent
        TheftTotalVehicle = 207 'ClaimLossType_Auto
        TowingAndLabor = 208 'ClaimLossType_Auto
        VandalismAndMischief = 209 'ClaimLossType_Auto
        Water = 204 'ClaimLossType_Auto
        Wind = 210 'ClaimLossType_Auto
    End Enum
    Enum ClaimLossType_CAP 'Commercial Auto; same values as ClaimLossType_Auto (also ClaimLossType_PPA) + LoadingOrUnloading (234) and UnderinsuredMotorist (262)
        AnimalCollision = 195 'ClaimLossType_Auto
        Earthquake = 196 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (63), ClaimLossType_Liability (63), and ClaimLossType (63)
        EnvironmentalSpill = 136 'ClaimLossType_Auto, ClaimLossType
        Explosion = 197 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (167), ClaimLossType_Liability (167), and ClaimLossType (48 - not used in Diamond)
        FallingObjectsOrMissiles = 198 'ClaimLossType_Auto
        Fire = 199 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (37), ClaimLossType_Liability (37), and ClaimLossType (37)
        Flood = 200 'ClaimLossType_Auto; same text but diff value in ClaimLossType (98 - not used in Diamond)
        GlassRepair = 201 'ClaimLossType_Auto
        GlassReplace = 202 'ClaimLossType_Auto
        Hail = 203 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (39), ClaimLossType_Liability (39), and ClaimLossType (39)
        LoadingOrUnloading = 234
        MultiVehicleAccident = 193 'ClaimLossType_Auto
        NonMovingVehicle = 212 'ClaimLossType_Auto
        OtherNOC = 211 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (251) and ClaimLossType_Liability (178)
        RiotOrCivilCommotion = 205 'ClaimLossType_Auto; same text but diff value in ClaimLossType_Property (183), ClaimLossType_Liability (183), and ClaimLossType (145 - not used in Diamond)
        SingleVehicleAccident = 194 'ClaimLossType_Auto
        TheftPartsOrContents = 206 'ClaimLossType_Auto:TheftPartsAndContent
        TheftTotalVehicle = 207 'ClaimLossType_Auto
        TowingAndLabor = 208 'ClaimLossType_Auto
        UnderinsuredMotorist = 262
        VandalismAndMischief = 209 'ClaimLossType_Auto; ClaimLossType_Property, ClaimLossType_Liability, and ClaimLossType has similar enum for VandalismAndMaliciousMischief (59)
        Water = 204 'ClaimLossType_Auto
        Wind = 210 'ClaimLossType_Auto
    End Enum
    Enum ClaimLossType_BOP 'Commercial BOP
        Aircraft = 184 'ClaimLossType_Property, ClaimLossType_Liability
        AnimalDamage = 254 'ClaimLossType_Property; same text but diff value in ClaimLossType_Liability (165) and ClaimLossType (65 - not used in Diamond)
        BackupOfSewerOrDrain = 41 'ClaimLossType_Property, ClaimLossType_Liability, ClaimLossType
        Burglary = 245
        Collapse = 247 'ClaimLossType_Property; same text but diff value in ClaimLossType_Liability (42) and ClaimLossType (42)
        CollisionUpsetOrOverturn = 258 'same text but diff value in ClaimLossType_Property (213); ClaimLossType has similar enum for CollisionUpsetOverturn (91 - not used in Diamond)
        Conversion = 162 'ClaimLossType
        DebrisRemoval = 257 'ClaimLossType_Property; same text but diff value in ClaimLossType_Liability (187)
        Earthquake = 63 'ClaimLossType_Property, ClaimLossType_Liability, ClaimLossType; same text but diff value in ClaimLossType_Auto (196)
        EmployeeDishonesty = 246
        Environmental = 46 'ClaimLossType_Property, ClaimLossType_Liability; same value but diff text in ClaimLossType (EnvironmentalMiscellaneous)
        EquipmentBreakdown = 248 'same text but diff value in ClaimLossType_Property (166), ClaimLossType_Liability (166), and ClaimLossType (47 - not used in Diamond)
        Explosion = 167 'ClaimLossType_Property, ClaimLossType_Liability; same text but diff value in ClaimLossType (48 - not used in Diamond)
        FallingObjects = 255 'ClaimLossType_Property; same text but diff value in ClaimLossType_Liability (185)
        FalseAlarm = 261 'ClaimLossType_Property; same text but diff value in ClaimLossType_Liability (66) and ClaimLossType (66)
        Fire = 37 'ClaimLossType_Property, ClaimLossType_Liability, ClaimLossType; same text but diff value in ClaimLossType_Auto (199)
        FloodMachineryAndImplements = 214 'ClaimLossType_Property
        Forgery = 142 'ClaimLossType
        Freezing = 182 'ClaimLossType_Property, ClaimLossType_Liability
        GlassBreakage = 249 'same text but diff value in ClaimLossType_Property (168), ClaimLossType_Liability (168), and ClaimLossType (50 - not used in Diamond)
        Hail = 39 'ClaimLossType_Property, ClaimLossType_Liability, ClaimLossType; same text but diff value in ClaimLossType_Auto (203)
        Landslide = 62 'ClaimLossType_Property, ClaimLossType_Liability, ClaimLossType
        LiabilityAdvertising = 153 'ClaimLossType
        LiabilityAnimalOrLivestock = 170 'ClaimLossType_Property; same text but diff value in ClaimLossType (81 - not used in Diamond)
        LiabilityCompletedOps = 241
        LiabilityDamageToPropertyOfOthers = 260 'same text but diff value in ClaimLossType_Liability (173)
        LiabilityEnvironmental = 172 'ClaimLossType_Liability; same text but diff value in ClaimLossType (75 - not used in Diamond)
        LiabilityFallingObjects = 243
        LiabilityIntellectualProperty = 238
        LiabilityLoadingOrUnloading = 236
        LiabilityMiscVehicle = 188 'ClaimLossType_Liability
        LiabilityNOC = 189 'ClaimLossType_Liability
        LiabilityPersonalInjury = 242 'same text but diff value in ClaimLossType_Liability (192)
        LiabilityPetBite = 239 'same text but diff value in ClaimLossType_Liability (171)
        LiabilityProducts = 240
        LiabilityServingOfAlcohol = 191 'ClaimLossType_Liability
        LiabilitySlipAndFall = 174 'ClaimLossType_Liability; same text but diff value in ClaimLossType (72)
        LiabilityWatercraft = 150 'ClaimLossType_Liability, ClaimLossType
        Lightning = 53 'ClaimLossType_Property, ClaimLossType_Liability, ClaimLossType
        LivestockOther = 216 'ClaimLossType_Property
        LivestockCollision = 217 'ClaimLossType_Property
        MineSubsidence = 250 'same text but diff value in ClaimLossType_Property (175), ClaimLossType_Liability (75), and ClaimLossType (54 - not used in Diamond)
        MysteriousDisappearance = 67 'ClaimLossType_Property, ClaimLossType_Liability, and ClaimLossType
        OtherNOC = 251 'ClaimLossType_Property; same text but diff value in ClaimLossType_Auto (211) and ClaimLossType_Liability (178)
        PowerInterruption = 252 'same text but diff value in ClaimLossType_Property (179) and ClaimLossType_Liability (179)
        RiotOrCivilCommotion = 183 'ClaimLossType_Property and ClaimLossType_Liability; same text but diff value in ClaimLossType_Auto (205) and ClaimLossType (145)
        RoadbedCollision = 259 'same text but diff value in ClaimLossType_Property (219)
        Robbery = 244
        Sinkhole = 64 'ClaimLossType_Property, ClaimLossType_Liability, and ClaimLossType
        Smoke = 40 'ClaimLossType_Property, ClaimLossType_Liability, and ClaimLossType
        Theft = 49 'ClaimLossType_Property, ClaimLossType_Liability; same value but diff text in ClaimLossType (TheftOther)
        VandalismAndMaliciousMischief = 59 'ClaimLossType_Property, ClaimLossType_Liability, and ClaimLossType; similar text but diff value in ClaimLossType_Auto (VandalismAndMischief - 209)
        VehicleDamage = 176 'ClaimLossType_Property, ClaimLossType_Liability; same text but diff value in ClaimLossType (60)
        WaterDamageAppliance = 180 'ClaimLossType_Property, ClaimLossType_Liability
        WaterDamageOther = 177 'ClaimLossType_Property, ClaimLossType_Liability
        WaterDamageWindDriven = 181 'ClaimLossType_Property, ClaimLossType_Liability
        WeightOfIceSnowOrSleet = 256 'ClaimLossType_Property; same text but diff value in ClaimLossType_Liability (186)
        WindOrTornado = 38 'ClaimLossType_Property, ClaimLossType_Liability, and ClaimLossType
    End Enum
    Enum ClaimLossType_CRM 'Commercial Crime
        Burglary = 245
        Conversion = 162
        EmployeeDishonesty = 246
        Forgery = 142
        OtherNOC = 251
        Robbery = 244
        Theft = 49
    End Enum
    Enum ClaimLossType_GAR 'Commercial Garage
        AnimalCollision = 195
        Earthquake = 196
        EnvironmentalSpill = 136
        Explosion = 197
        FallingObjectsOrMissiles = 198
        Fire = 199
        Flood = 200
        GarageKeepersLiability = 235
        GlassRepair = 201
        GlassReplace = 202
        Hail = 203
        LiabilityAdvertising = 153
        LiabilityAnimalOrLivestock = 170
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityEnvironmental = 172
        LiabilityIntellectualProperty = 238
        LiabilityLoadingOrUnloading = 236
        LiabilityNOC = 189
        LiabilityPersonalInjury = 192
        LiabilityPetBite = 171
        LiabilityProductsOrCompletedOps = 237
        LiabilityServingOfAlcohol = 191
        LiabilityWatercraft = 150
        LoadingOrUnloading = 234
        MultiVehicleAccident = 193
        NonMovingVehicle = 212
        OtherNOC = 211
        RiotOrCivilCommotion = 205
        SingleVehicleAccident = 194
        TheftPartsOrContents = 206
        TheftTotalVehicle = 207
        TowingAndLabor = 208
        VandalismAndMischief = 209
        Water = 204
        Wind = 210
    End Enum
    Enum ClaimLossType_CGL 'Commercial General Liability
        LiabilityAdvertising = 153
        LiabilityAnimalOrLivestock = 170
        LiabilityCompletedOps = 241
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityEnvironmental = 172
        LiabilityFallingObjects = 243
        LiabilityIntellectualProperty = 238
        LiabilityLoadingOrUnloading = 236
        LiabilityMiscVehicle = 188
        LiabilityNOC = 189
        LiabilityPersonalInjury = 242
        LiabilityPetBite = 239
        LiabilityProducts = 240
        LiabilityServingOfAlcohol = 191
        LiabilitySlipAndFall = 174
        LiabilityWatercraft = 150
    End Enum
    Enum ClaimLossType_CIM 'Commercial Inland Marine
        Aircraft = 184
        AnimalDamage = 254
        BackupOfSewerOrDrain = 41
        Collapse = 247
        CollisionUpsetOrOverturn = 213
        DebrisRemoval = 257
        Earthquake = 63
        Environmental = 46
        EquipmentBreakdown = 166
        Explosion = 167
        FallingObjects = 255
        FalseAlarm = 261
        Fire = 37
        FloodMachineryAndImplements = 214
        Freezing = 182
        GlassBreakage = 168
        Hail = 39
        Landslide = 62
        Lightning = 53
        MineSubsidence = 175
        MysteriousDisappearance = 67
        OtherNOC = 251
        PowerInterruption = 179
        RiotOrCivilCommotion = 183
        Sinkhole = 64
        Smoke = 40
        Theft = 49
        VandalismAndMaliciousMischief = 59
        VehicleDamage = 176
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        WeightOfIceSnowOrSleet = 256
        WindOrTornado = 38
    End Enum
    Enum ClaimLossType_CPR 'Commercial Property
        Aircraft = 184
        AnimalDamage = 254
        BackupOfSewerOrDrain = 41
        Collapse = 247
        CollisionUpsetOrOverturn = 213
        DebrisRemoval = 257
        Earthquake = 63
        Environmental = 46
        EquipmentBreakdown = 166
        Explosion = 167
        FallingObjects = 255
        FalseAlarm = 261
        Fire = 37
        FloodMachineryAndImplements = 214
        Freezing = 182
        GlassBreakage = 168
        Hail = 39
        Landslide = 62
        Lightning = 53
        LivestockOther = 216
        LivestockCollision = 217
        MineSubsidence = 175
        MysteriousDisappearance = 67
        OtherNOC = 251
        PowerInterruption = 179
        RiotOrCivilCommotion = 183
        RoadbedCollision = 219
        Sinkhole = 64
        Smoke = 40
        Theft = 49
        VandalismAndMaliciousMischief = 59
        VehicleDamage = 176
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        WeightOfIceSnowOrSleet = 256
        WindOrTornado = 38
    End Enum
    Enum ClaimLossType_CUP 'Commercial Umbrella
        BOP = 229
        CGL = 230
        CommercialAuto = 227
        CommercialGarage = 228
        DwellingFire = 225
        Farmowners = 226
        Homeowners = 224
        PersonalAuto = 223
        WorkersCompensation = 231
    End Enum
    Enum ClaimLossType_DFR 'Dwelling Fire Personal
        Aircraft = 184
        AnimalDamage = 165
        BackupOfSewerOrDrain = 41
        Collapse = 42
        DebrisRemoval = 187
        Earthquake = 63
        Environmental = 46
        EquipmentBreakdown = 166
        Explosion = 167
        FallingObjects = 185
        FalseAlarm = 66
        Fire = 37
        Freezing = 182
        GlassBreakage = 168
        Hail = 39
        IdentityTheft = 169
        Landslide = 62
        LiabilityAnimalOrLivestock = 170
        LiabilityBusinessPursuits = 73
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityEnvironmental = 172
        LiabilityMiscVehicle = 188
        LiabilityNOC = 189
        LiabilityPersonalInjury = 192
        LiabilityPetBite = 171
        LiabilityServingOfAlcohol = 191
        LiabilitySlipAndFall = 174
        LiabilityTrampoline = 190
        LiabilityWatercraft = 150
        Lightning = 53
        MineSubsidence = 175
        MysteriousDisappearance = 67
        OtherNOC = 178
        PowerInterruption = 179
        RiotOrCivilCommotion = 183
        Sinkhole = 64
        Smoke = 40
        Theft = 49
        VandalismAndMaliciousMischief = 59
        VehicleDamage = 176
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        WeightOfIceSnowOrSleet = 186
        WindOrTornado = 38
    End Enum
    Enum ClaimLossType_FAR 'Farm
        Aircraft = 184
        AnimalDamage = 165
        BackupOfSewerOrDrain = 41
        Collapse = 42
        CollisionUpsetOrOverturn = 213
        DebrisRemoval = 187
        Earthquake = 63
        EmployersLiability = 221
        Environmental = 46
        EquipmentBreakdown = 166
        Explosion = 167
        FallingObjects = 185
        FalseAlarm = 66
        FamilyMedical = 220
        Fire = 37
        FloodMachineryAndImplements = 214
        Freezing = 182
        GlassBreakage = 168
        Hail = 39
        IdentityTheft = 169
        IntakeOfForeignObjects = 215
        Landslide = 62
        LiabilityAnimalOrLivestock = 170
        LiabilityBusinessPursuits = 73
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityEnvironmental = 172
        LiabilityMiscVehicle = 188
        LiabilityNOC = 189
        LiabilityPersonalInjury = 192
        LiabilityPetBite = 171
        LiabilityServingOfAlcohol = 191
        LiabilitySlipAndFall = 174
        LiabilityTrampoline = 190
        LiabilityWatercraft = 150
        Lightning = 53
        LivestockOther = 216
        LivestockCollision = 217
        MineSubsidence = 175
        MysteriousDisappearance = 67
        OtherNOC = 178
        PowerInterruption = 179
        RiotOrCivilCommotion = 183
        RoadbedCollision = 219
        Sinkhole = 64
        Smoke = 40
        Theft = 49
        VandalismAndMaliciousMischief = 59
        VehicleDamage = 176
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        WeightOfIceSnowOrSleet = 186
        WindOrTornado = 38
        WorkersCompensation = 218
    End Enum
    Enum ClaimLossType_HOM 'Home Personal
        Aircraft = 184
        AnimalDamage = 165
        BackupOfSewerOrDrain = 41
        Collapse = 42
        DebrisRemoval = 187
        Earthquake = 63
        Environmental = 46
        EquipmentBreakdown = 166
        Explosion = 167
        FallingObjects = 185
        FalseAlarm = 66
        Fire = 37
        Freezing = 182
        GlassBreakage = 168
        Hail = 39
        IdentityTheft = 169
        Landslide = 62
        LiabilityAnimalOrLivestock = 170
        LiabilityBusinessPursuits = 73
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityEnvironmental = 172
        LiabilityMiscVehicle = 188
        LiabilityNOC = 189
        LiabilityPersonalInjury = 192
        LiabilityPetBite = 171
        LiabilityServingOfAlcohol = 191
        LiabilitySlipAndFall = 174
        LiabilityTrampoline = 190
        LiabilityWatercraft = 150
        Lightning = 53
        MineSubsidence = 175
        MysteriousDisappearance = 67
        OtherNOC = 178
        PowerInterruption = 179
        RiotOrCivilCommotion = 183
        Sinkhole = 64
        Smoke = 40
        Theft = 49
        VandalismAndMaliciousMischief = 59
        VehicleDamage = 176
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        WeightOfIceSnowOrSleet = 186
        WindOrTornado = 38
    End Enum
    Enum ClaimLossType_PIM 'Inland Marine Personal
        AnimalDamage = 165
        CollisionUpsetOrOverturn = 213
        Fire = 37
        FloodMachineryAndImplements = 214
        LostStone = 222
        MysteriousDisappearance = 67
        OtherNOC = 178
        Theft = 49
    End Enum
    Enum ClaimLossType_PUP 'Umbrella Personal
        BOP = 229
        CGL = 230
        CommercialAuto = 227
        CommercialGarage = 228
        DwellingFire = 225
        Farmowners = 226
        Homeowners = 224
        PersonalAuto = 223
        WorkersCompensation = 231
    End Enum
    Enum ClaimLossType_WCP 'Workers Comp
        EmployersLiability = 233
        WorkComp = 232
    End Enum
    Enum PolicyLobType 'uses Diamond's Lob.lob_id
        AutoPersonal = 1
        CommercialAuto = 20
        CommercialBOP = 25
        CommercialCrime = 26
        CommercialGarage = 24
        CommercialGeneralLiability = 9
        CommercialInlandMarine = 29
        CommercialPackage = 23
        CommercialProperty = 28
        CommercialUmbrella = 27
        DwellingFirePersonal = 3
        Farm = 17
        HomePersonal = 2
        InlandMarinePersonal = 16
        NotAssigned = 0
        UmbrellaPersonal = 14
        WorkersComp = 21
    End Enum
    'added 8/3/2017
    Enum ClaimLossType_AllValid
        Aircraft = 184
        AnimalCollision = 195
        AnimalDamage = 165
        AnimalDamage2 = 254
        BackupOfSewerOrDrain = 41
        BOP = 229
        Burglary = 245
        CGL = 230
        Collapse = 42
        Collapse2 = 247
        CollisionUpsetOrOverturn = 213
        CollisionUpsetOrOverturn2 = 258
        CommercialAuto = 227
        CommercialGarage = 228
        Conversion = 162
        DebrisRemoval = 187
        DebrisRemoval2 = 257
        DwellingFire = 225
        Earthquake = 63
        Earthquake2 = 196
        EmployeeDishonesty = 246
        EmployersLiability = 221
        EmployersLiability2 = 233
        Environmental = 46
        EnvironmentalSpill = 136
        EquipmentBreakdown = 166
        EquipmentBreakdown2 = 248
        Explosion = 167
        Explosion2 = 197
        FallingObjects = 185
        FallingObjects2 = 255
        FallingObjectsOrMissiles = 198
        FalseAlarm = 66
        FalseAlarm2 = 261
        FamilyMedical = 220
        Farmowners = 226
        Fire = 37
        Fire2 = 199
        Flood = 200
        FloodMachineryAndImplements = 214
        Forgery = 142
        Freezing = 182
        GarageKeepersLiability = 235
        GlassBreakage = 168
        GlassBreakage2 = 249
        GlassRepair = 201
        GlassReplace = 202
        Hail = 39
        Hail2 = 203
        Homeowners = 224
        IdentityTheft = 169
        IntakeOfForeignObjects = 215
        Landslide = 62
        LiabilityAdvertising = 153
        LiabilityAnimalOrLivestock = 170
        LiabilityBusinessPursuits = 73
        LiabilityCompletedOps = 241
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityDamageToPropertyOfOthers2 = 260
        LiabilityEnvironmental = 172
        LiabilityFallingObjects = 243
        LiabilityIntellectualProperty = 238
        LiabilityLoadingOrUnloading = 236
        LiabilityMiscVehicle = 188
        LiabilityNOC = 189
        LiabilityPersonalInjury = 192
        LiabilityPersonalInjury2 = 242
        LiabilityPetBite = 171
        LiabilityPetBite2 = 239
        LiabilityProducts = 240
        LiabilityProductsOrCompletedOps = 237
        LiabilityServingOfAlcohol = 191
        LiabilitySlipAndFall = 174
        LiabilityTrampoline = 190
        LiabilityWatercraft = 150
        Lightning = 53
        LivestockOther = 216
        LivestockCollision = 217
        LoadingOrUnloading = 234
        LostStone = 222
        MineSubsidence = 175
        MineSubsidence2 = 250
        MultiVehicleAccident = 193
        MysteriousDisappearance = 67
        NonMovingVehicle = 212
        OtherNOC = 178
        OtherNOC2 = 211
        OtherNOC3 = 251
        PersonalAuto = 223
        PowerInterruption = 179
        PowerInterruption2 = 252
        RiotOrCivilCommotion = 183
        RiotOrCivilCommotion2 = 205
        RoadbedCollision = 219
        RoadbedCollision2 = 259
        Robbery = 244
        SingleVehicleAccident = 194
        Sinkhole = 64
        Smoke = 40
        Theft = 49
        TheftPartsOrContents = 206
        TheftTotalVehicle = 207
        TowingAndLabor = 208
        UnderinsuredMotorist = 262
        VandalismAndMischief = 209
        VandalismAndMaliciousMischief = 59
        VehicleDamage = 176
        Water = 204
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        WeightOfIceSnowOrSleet = 186
        WeightOfIceSnowOrSleet2 = 256
        Wind = 210
        WindOrTornado = 38
        WorkComp = 232
        WorkersCompensation = 218
        WorkersCompensation2 = 231
    End Enum
    Enum ClaimLossType_All
        AccidentalDischargeOrLeakage = 87
        Aircraft = 184
        AircraftDamage = 144
        AllOther = 88
        AllOtherPhysicalDamage = 89
        Alteration = 157
        AnimalCollision = 195
        AnimalDamage = 65
        AnimalDamage2 = 165
        AnimalDamage3 = 254
        ApplianceRelatedWaterDamage = 90
        BackupOfSewerOrDrain = 41
        BodilyInjuryAutoBI = 152
        BOP = 229
        BroadFormPerilsAutoPAPDOrOTC = 86
        Burglary = 245
        CGL = 230
        Collapse = 42
        Collapse2 = 247
        CollisionMultipleAutos = 113
        CollisionOther = 114
        CollisionSingleAuto = 115
        CollisionUpsetOrOverturn = 91
        CollisionUpsetOrOverturn2 = 213
        CollisionUpsetOrOverturn3 = 258
        CommercialAuto = 227
        CommercialGarage = 228
        ComprehensiveAnimal = 116
        ComprehensiveEarthquake = 117
        ComprehensiveExplosion = 118
        ComprehensiveFallingObjectsOrMissiles = 119
        ComprehensiveFire = 120
        ComprehensiveFlood = 121
        ComprehensiveGlassRepair = 122
        ComprehensiveGlassReplace = 123
        ComprehensiveHail = 124
        ComprehensiveLabor = 125
        ComprehensiveOther = 126
        ComprehensiveOtherTransportation = 127
        ComprehensiveOtherWater = 128
        ComprehensiveRiotOrCivilCommotion = 129
        ComprehensiveTheftPartial = 130
        ComprehensiveTheftTotal = 131
        ComprehensiveTowing = 132
        ComprehensiveVandalismAndMischief = 133
        ComprehensiveWind = 134
        ComputerFraud = 161
        Contamination = 143
        ContaminationOrPollution = 92
        Conversion = 162
        CreditCard = 93
        DamageToPropertyOfOthers = 94
        DeathAndDisabilityOrFuneral = 135
        DebrisRemoval = 187
        DebrisRemoval2 = 257
        DestructionOfDataOrPrograms = 164
        DogBiteLiability = 95
        DwellingFire = 225
        Earthmovement = 96
        Earthquake = 63
        Earthquake2 = 196
        EmployeeDishonesty = 246
        EmployeeTheft = 160
        EmployersLiability = 221
        EmployersLiability2 = 233
        Environmental = 46
        EnvironmentalMiscellaneous = 139
        EnvironmentalSpill = 136
        EnvironmentalMold = 44
        EnvironmentalOther = 43
        EnvironmentalPetroleum = 45
        EquipmentBreakdown = 47
        EquipmentBreakdown2 = 166
        EquipmentBreakdown3 = 248
        Explosion = 48
        Explosion2 = 167
        Explosion3 = 197
        ExtendedCoveragePerils = 97
        FallingObjects = 185
        FallingObjects2 = 255
        FallingObjectsOrMissiles = 198
        FalseAlarm = 66
        FalseAlarm2 = 261
        FamilyMedical = 220
        Farmowners = 226
        Fire = 37
        Fire2 = 199
        FireAutoPAPDOrOTC = 84
        Flood = 98
        Flood2 = 200
        FloodMachineryAndImplements = 214
        Forgery = 142
        ForgeryOrAlteration = 158
        Freezing = 182
        FreezingWaterAndSubsequentWater = 99
        GarageKeepersLiability = 235
        GlassBreakage = 50
        GlassBreakage2 = 168
        GlassBreakage3 = 249
        GlassRepair = 201
        GlassReplace = 202
        Hail = 39
        Hail2 = 203
        Homeowners = 224
        IdentityTheft = 51
        IdentityTheft2 = 169
        InlandMarine = 52
        IntakeOfForeignObject = 100
        IntakeOfForeignObjects = 215
        Landslide = 62
        LiabilityAllOther = 101
        LiabilityAbuseOrMolestation = 147
        LiabilityAdvertising = 153
        LiabilityAnimalOrLivestock = 81
        LiabilityAnimalOrLivestock2 = 170
        LiabilityBodilyInjury = 69
        LiabilityBusinessPursuits = 73
        LiabilityCollision = 74
        LiabilityCompletedOps = 241
        LiabilityDamageToPropertyOfOthers = 173
        LiabilityDamageToPropertyOfOthers2 = 260
        LiabilityDogBite = 71
        LiabilityEnvironmental = 75
        LiabilityEnvironmental2 = 172
        LiabilityEnvironmentalMiscellaneous = 79
        LiabilityEnvironmentalMold = 76
        LiabilityEnvironmentalPetroleum = 77
        LiabilityEnvironmentalSolidWaste = 78
        LiabilityErrorsOrOmissions = 148
        LiabilityFallingObjects = 243
        LiabilityGlass = 80
        LiabilityIntellectualProperty = 238
        LiabilityLoadingOrUnloading = 236
        LiabilityMedPay = 68
        LiabilityMiscVehicle = 188
        LiabilityMiscellaneous = 82
        LiabilityNOC = 189
        LiabilityOtherAnimal = 154
        LiabilityOverspray = 149
        LiabilityOwnersProtectiveLiability = 155
        LiabilityPersonal = 156
        LiabilityPersonalInjury = 192
        LiabilityPersonalInjury2 = 242
        LiabilityPersonalTheft = 83
        LiabilityPetBite = 171
        LiabilityPetBite2 = 239
        LiabilityProducts = 240
        LiabilityProductsOrCompletedOps = 237
        LiabilityPropertyDamage = 70
        LiabilityServingOfAlcohol = 191
        LiabilitySlipAndFall = 72
        LiabilitySlipAndFall2 = 174
        LiabilityTrampoline = 190
        LiabilityWatercraft = 150
        LiabilityBodilyInjury2 = 140
        LiabilityPropertyDamage2 = 141
        Lightning = 53
        Livestock = 102
        LivestockOther = 216
        LivestockCollision = 217
        LoadingOrUnloading = 234
        LossAdjustmentExpense = 103
        LostStone = 222
        MedicalPayments = 104
        MineSubsidence = 54
        MineSubsidence2 = 175
        MineSubsidence3 = 250
        Miscellaneous = 55
        Mold = 105
        MultiVehicleAccident = 193
        MysteriousDisappearance = 67
        MysteriousDisappearanceInvolvingScheduledProperty = 106
        NOrA = 0
        NonMovingVehicle = 212
        OtherNOC = 178
        OtherNOC2 = 211
        OtherNOC3 = 251
        PersonalAuto = 223
        PowerInterruption = 179
        PowerInterruption2 = 252
        PowerInterruptionOffPremise = 58
        PowerInterruptionOnPremise = 57
        RiotOrCivilCommotion = 183
        RiotOrCivilCommotion2 = 145
        RiotOrCivilCommotion3 = 205
        RoadbedCollision = 219
        RoadbedCollision2 = 259
        Robbery = 244
        SingleVehicleAccident = 194
        Sinkhole = 64
        SlipOrFallLiability = 107
        Smoke = 40
        SprinklerLeakage = 146
        Suffocation = 151
        Theft = 49
        TheftPartsOrContents = 206
        TheftTotalVehicle = 207
        TheftOfMoney = 56
        TheftOfMoneyAndSecurities = 159
        TheftOrInvolvingScheduledProperty = 108
        TheftAutoPAPDOrOTC = 85
        TheftOrBurglary = 109
        TowingAndLabor = 208
        UnauthorizedReproduction = 163
        UnderinsuredMotorist = 262
        UninsuredMotoristBodilyInjury = 137
        UninsuredMotoristPropertyDamage = 138
        VandalismAndMischief = 209
        VandalismAndMaliciousMischief = 59
        VehicleDamage = 60
        VehicleDamage2 = 176
        Water = 204
        WaterDamage = 61
        WaterDamageAppliance = 180
        WaterDamageOther = 177
        WaterDamageWindDriven = 181
        Watercraft = 110
        WeatherRelatedWaterDamage = 111
        WeightOfIceSnowOrSleet = 186
        WeightOfIceSnowOrSleet2 = 256
        Wind = 210
        WindOrTornado = 38
        WorkComp = 232
        WorkersCompensation = 218
        WorkersCompensation2 = 231
        WorkersCompensation3 = 112
    End Enum

    Enum ClaimLossIndicatorType
        None = 0
        PartialLoss = 1
        TotalLoss = 2
    End Enum

    Enum ClaimLocationOfLoss
        OnPremises = 1
        OffPremises = 2
        Unknown = 3
    End Enum

    Enum DwellingType
        NotAvailable = 0
        OneFamilyDwelling = 1
        TwoFamilyDwelling = 2
        ThreeFamilyDwelling = 3
        FourFamilyDwelling = 4
        Apartment1to10Units = 5
        Farm = 6
        VacantLand = 7
        LessorsRisk = 8
        OtherBusinessProperty = 9
        Frame = 10
        Masonry = 11
        FireResistant = 12
        MasonryVeneer = 13
        RentersPolicy = 14
        CondominiumUnit = 15
        ManufacturedSingleWide = 16
        ManufacturedDoubleWide = 17
        SiteBuiltFrame = 18
        SiteBuiltMasonry = 19
        IncidentalBusinessExposuresOffices = 20
        IncidentalBusinessExposuresRentalDwelling = 21
        Type1 = 22
        Type2 = 23
        Type3 = 24
        SuperiorConstructionFireResistive = 25
        SuperiorConstructionMasonryNonCombustible = 26
        SuperiorConstructionNonCombustible = 27
    End Enum

    Enum UserLocation
        Diamond
        DiamondAndLegacy
        DiamondAndQuotemaster
        Legacy
        LegacyAndQuotemaster
        Quotemaster
        AllSystems
        None
    End Enum

    Enum Validation
        Username
        Password
    End Enum

    Enum Criteria
        LowercaseLetter
        UppercaseLetter
        Number
    End Enum

    Enum ErrorLevel
        Warning
        Severe
        Minor
        Validation
        Programmer
    End Enum

    Enum State
        ALASKA = 1
        ALABAMA = 2
        ARKANSAS = 3
        ARIZONA = 4
        CALIFORNIA = 5
        COLORADO = 6
        CONNECTICUT = 7
        DELAWARE = 9
        FLORIDA = 10
        GEORGIA = 11
        HAWAII = 12
        IOWA = 13
        IDAHO = 14
        ILLINOIS = 15
        INDIANA = 16
        KANSAS = 17
        KENTUCKY = 18
        LOUISIANA = 19
        MASSACHUSETTS = 20
        MARYLAND = 21
        MAINE = 22
        MICHIGAN = 23
        MINNESOTA = 24
        MISSOURI = 25
        MISSISSIPPI = 26
        MONTANA = 27
        NORTH_CAROLINA = 28
        NORTH_DAKOTA = 29
        NEBRASKA = 30
        NEW_HAMPSHIRE = 31
        NEW_JERSEY = 32
        NEW_MEXICO = 33
        NEVADA = 34
        NEW_YORK = 35
        OHIO = 36
        OKLAHOMA = 37
        OREGON = 38
        PENNSYLVANIA = 39
        RHODE_ISLAND = 40
        SOUTH_CAROLINA = 41
        SOUTH_DAKOTA = 42
        TENNESSEE = 43
        TEXAS = 44
        UTAH = 45
        VIRGINIA = 46
        VERMONT = 47
        WASHINGTON = 48
        WISCONSIN = 49
        WEST_VIRGINIA = 50
        WYOMING = 51
    End Enum

    Public Sub New()

    End Sub
End Class
