'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlProperty_HOM

    '''<summary>
    '''PolicyInfoDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyInfoDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMainHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkClearGeneralInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClearGeneralInfo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSaveGeneralInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveGeneralInfo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ctlProperty_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlProperty_Address As Global.IFM.VR.Web.ctlProperty_Address

    '''<summary>
    '''ctlResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlResidence As Global.IFM.VR.Web.ctlResidence

    '''<summary>
    '''ctlMobileHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlMobileHome As Global.IFM.VR.Web.ctlMobileHome

    '''<summary>
    '''ctlProtectionClass_HOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlProtectionClass_HOM As Global.IFM.VR.Web.ctlProtectionClass_HOM

    '''<summary>
    '''ctlAccidentHistoryList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlAccidentHistoryList As Global.IFM.VR.Web.ctlAccidentHistoryList

    '''<summary>
    '''ctl_AdditionalInterest_MiniSerach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AdditionalInterest_MiniSerach As Global.IFM.VR.Web.ctl_AdditionalInterest_MiniSerach

    '''<summary>
    '''ctlVehicleAdditionalInterestList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlVehicleAdditionalInterestList As Global.IFM.VR.Web.ctlVehicleAdditionalInterestList

    '''<summary>
    '''ctl_Billing_Info_PPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Billing_Info_PPA As Global.IFM.VR.Web.ctl_Billing_Info_PPA

    '''<summary>
    '''ctlPropertyAdditionalQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPropertyAdditionalQuestions As Global.IFM.VR.Web.ctlPropertyAdditionalQuestions

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''divActionButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divActionButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveGotoNextSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveGotoNextSection As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRateHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRateHome As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divEndorsementButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEndorsementButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnMakeAChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMakeAChange As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewGotoNextSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewGotoNextSection As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
