'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlPropertyAdditionalQuestions

    '''<summary>
    '''AdditionalQuestionsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdditionalQuestionsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkClearAdditionalQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClearAdditionalQuestions As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSaveAdditionalQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveAdditionalQuestions As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''trQuestion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkHasAutoPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHasAutoPolicy As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trQuestion10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion10 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkFirstWrittenDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFirstWrittenDate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtFirstWrittenDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstWrittenDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trQuestion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkAnyChildren control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAnyChildren As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trQuestion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkSmokeAlarms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSmokeAlarms As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trQuestion4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddBurglarAlarmType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddBurglarAlarmType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trQuestion5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddFireAlarmType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddFireAlarmType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trQuestion6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddSprinklerType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSprinklerType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trQuestion6b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion6b As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkSprinkler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSprinkler As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trQuestion7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion7 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkTrampoline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTrampoline As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divNumOfTrampolines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNumOfTrampolines As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNumOfTrampolines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumOfTrampolines As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trQuestion8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion8 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkSwimmingPool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSwimmingPool As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divNumOfSwimmingPools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNumOfSwimmingPools As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNumOfSwimmingPools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumOfSwimmingPools As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trQuestion9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion9 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkWoodStove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWoodStove As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divNumOfWoodburningStoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNumOfWoodburningStoves As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNumOfWoodburningStoves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumOfWoodburningStoves As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSolidFuelQuestionnaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolidFuelQuestionnaire As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divWoodburningInfoSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWoodburningInfoSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWoodBurningInfoMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWoodBurningInfoMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWoodBurningEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWoodBurningEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trQuestion11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trQuestion11 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkMortgageContractSeller control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMortgageContractSeller As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''HiddenField5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField5 As Global.System.Web.UI.WebControls.HiddenField
End Class
