'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_Master_Edit

    '''<summary>
    '''ctlUWQuestionsPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlUWQuestionsPopup As Global.IFM.VR.Web.ctlUWQuestionsPopup

    '''<summary>
    '''ctlDisplayDiamondRatingErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDisplayDiamondRatingErrors As Global.IFM.VR.Web.ctlDisplayDiamondRatingErrors

    '''<summary>
    '''ctlEffectiveDateChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEffectiveDateChecker As Global.IFM.VR.Web.ctlEffectiveDateChecker

    '''<summary>
    '''ctl_Personal_NewQuoteForClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Personal_NewQuoteForClient As Global.IFM.VR.Web.ctl_Personal_NewQuoteForClient

    '''<summary>
    '''ctlIsuredList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlIsuredList As Global.IFM.VR.Web.ctlIsuredList

    '''<summary>
    '''ctlPrefill_PPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPrefill_PPA As Global.IFM.VR.Web.ctlPrefill_PPA

    '''<summary>
    '''ctlDriverList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDriverList As Global.IFM.VR.Web.ctlDriverList

    '''<summary>
    '''ctlVehicleList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlVehicleList As Global.IFM.VR.Web.ctlVehicleList

    '''<summary>
    '''ctlCoverage_PPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCoverage_PPA As Global.IFM.VR.Web.ctlCoverage_PPA

    '''<summary>
    '''ctlQsummary_PPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlQsummary_PPA As Global.IFM.VR.Web.ctlQsummary_PPA

    '''<summary>
    '''ctlPrintHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPrintHistory As Global.IFM.VR.Web.ctlPrintHistory

    '''<summary>
    '''ctlPolicyHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPolicyHistory As Global.IFM.VR.Web.ctlPolicyHistory

    '''<summary>
    '''ctlBillingInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlBillingInfo As Global.IFM.VR.Web.ctlBillingInfo

    '''<summary>
    '''ctl_AttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AttachmentUpload As Global.IFM.VR.Web.ctl_AttachmentUpload
End Class
