'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlAccidentHistoryItem
    
    '''<summary>
    '''lblAccordianHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccordianHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRemove As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddLostType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddLostType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtLossDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLossDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAmountOfLoss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountOfLoss As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trFaultRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFaultRow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddFaultIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddFaultIndicator As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trLossDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLossDescription As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtLossDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLossDescription As Global.System.Web.UI.WebControls.TextBox
End Class
