'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlQsummary_PPA_Vehicle

    '''<summary>
    '''divQSummaryVItemt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQSummaryVItemt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVehClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehClass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVehicleSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVehicleSummary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlComp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Comp_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Comp_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Comp_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Comp_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCollision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCollision As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Collision_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Collision_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Collision_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Collision_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlTowing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTowing As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Towing_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Towing_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Towing_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Towing_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlRental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRental As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Transportation_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Transportation_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Transportation_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Transportation_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlTrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTrip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTripVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTripVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTripPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTripPrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPoliceTrainingFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPoliceTrainingFee As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdCovName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdCovName As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblPoliceTrainingFeePrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPoliceTrainingFeePrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSound As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSoundVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoundVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoundPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoundPrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAV As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_AV_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_AV_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_AV_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_AV_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMedia As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Media_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Media_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Media_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Media_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLoan As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Loan_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Loan_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Loan_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Loan_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlUMPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUMPD As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_UMPD_Limit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_UMPD_Limit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_UMPD_Val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_UMPD_Val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_UMPD_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_UMPD_Prem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPollution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPollution As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPollutionVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPollutionVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPollutionPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPollutionPrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCustom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustom As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCustomVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomPrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlCustomEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomEquip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCustomEquipVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomEquipVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomEquipPrem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomEquipPrem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hiddenvListActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenvListActive As Global.System.Web.UI.WebControls.HiddenField
End Class
