'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_WorkflowManager_App_BOP
    
    '''<summary>
    '''ctlDisplayDiamondRatingErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDisplayDiamondRatingErrors As Global.IFM.VR.Web.ctlDisplayDiamondRatingErrors
    
    '''<summary>
    '''ctlTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlTreeView As Global.IFM.VR.Web.ctlTreeView
    
    '''<summary>
    '''ctlCommercialUWQuestionList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCommercialUWQuestionList As Global.IFM.VR.Web.ctlCommercialUWQuestionList
    
    '''<summary>
    '''ctl_AttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AttachmentUpload As Global.IFM.VR.Web.ctl_AttachmentUpload
    
    '''<summary>
    '''ctl_AppSection_BOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AppSection_BOP As Global.IFM.VR.Web.ctl_AppSection_BOP
    
    '''<summary>
    '''ctl_BOP_QuoteSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_BOP_QuoteSummary As Global.IFM.VR.Web.ctl_BOP_QuoteSummary
    
    '''<summary>
    '''Ctl_PF_BOPQuoteSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ctl_PF_BOPQuoteSummary As Global.IFM.VR.Web.ctl_BOP_PFSummary
    
    '''<summary>
    '''wf_returnButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wf_returnButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ctl_ReturnToQuoteSide1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_ReturnToQuoteSide1 As Global.IFM.VR.Web.ctl_ReturnToQuoteSide
    
    '''<summary>
    '''ctlCommercial_IRPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCommercial_IRPM As Global.IFM.VR.Web.ctlCommercial_IRPM
    
    '''<summary>
    '''ctlCommercial_DocPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCommercial_DocPrint As Global.IFM.VR.Web.ctlCommercial_DocPrint
End Class
