'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_AppSection_BOP

    '''<summary>
    '''div_master_bop_app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_bop_app As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ctl_App_Policyholder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_App_Policyholder As Global.IFM.VR.Web.ctl_AppPolicyholder

    '''<summary>
    '''ctl_AddlPolicyholderList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AddlPolicyholderList As Global.IFM.VR.Web.ctl_App_AdditionalPolicyholderList

    '''<summary>
    '''ctl_BOP_NaicsCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_BOP_NaicsCode As Global.IFM.VR.Web.ctl_BOP_NaicsCode

    '''<summary>
    '''ctl_AdditionalInterestList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AdditionalInterestList As Global.IFM.VR.Web.ctlVehicleAdditionalInterestList

    '''<summary>
    '''ctl_AdditionalInterest_MiniSerach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AdditionalInterest_MiniSerach As Global.IFM.VR.Web.ctl_AdditionalInterest_MiniSerach

    '''<summary>
    '''ctl_LocationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_LocationList As Global.IFM.VR.Web.ctl_BOP_App_LocationList

    '''<summary>
    '''ctl_App_AdditionalInsureds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_App_AdditionalInsureds As Global.IFM.VR.Web.ctl_App_AdditionalInsureds

    '''<summary>
    '''ctl_ContractorsEQList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_ContractorsEQList As Global.IFM.VR.Web.ctl_App_CTEQList

    '''<summary>
    '''ctl_PhotogEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_PhotogEquip As Global.IFM.VR.Web.ctl_App_PhotographersEquipment

    '''<summary>
    '''ctl_BOP_App_AdditionalServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_BOP_App_AdditionalServices As Global.IFM.VR.Web.ctl_BOP_App_AdditionalServices

    '''<summary>
    '''ctlAccidentHistoryList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlAccidentHistoryList As Global.IFM.VR.Web.ctlAccidentHistoryList

    '''<summary>
    '''ctl_Prior_CarrierPPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Prior_CarrierPPA As Global.IFM.VR.Web.ctl_Prior_Carrier_PPA

    '''<summary>
    '''ctl_Billing_Info_PPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Billing_Info_PPA As Global.IFM.VR.Web.ctl_Billing_Info_PPA

    '''<summary>
    '''ctl_Esignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Esignature As Global.IFM.VR.Web.ctl_Esignature

    '''<summary>
    '''ctlProducer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlProducer As Global.IFM.VR.Web.ctl_Producer

    '''<summary>
    '''ctlApp_Rate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlApp_Rate As Global.IFM.VR.Web.ctl_App_Rate

    '''<summary>
    '''hiddendiv_master_bop_app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddendiv_master_bop_app As Global.System.Web.UI.WebControls.HiddenField
End Class
