'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_WCP_Coverages

    '''<summary>
    '''divMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divGeneralInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGeneralInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkSaveGeneralInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveGeneralInfo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ddlEmployersLiability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmployersLiability As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExpMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpMod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExpModEffDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpModEffDt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bdpExpModEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bdpExpModEffDate As Global.BasicFrame.WebControls.BasicDatePicker

    '''<summary>
    '''divLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ctl_WCP_LocationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_WCP_LocationList As Global.IFM.VR.Web.ctl_WCP_LocationList

    '''<summary>
    '''divClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divClassification As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbAddNewClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAddNewClassification As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSaveClassifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveClassifications As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divClassificationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divClassificationList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptClassifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptClassifications As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divEndorsements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEndorsements As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkSaveEndorsements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveEndorsements As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkInclusionOfSoleProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInclusionOfSoleProp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblInclusionOfSoleProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInclusionOfSoleProp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trBlanketWaiverOfSubroRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBlanketWaiverOfSubroRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkBlanketWaiverOfSubro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBlanketWaiverOfSubro As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblBlanketWaiverOfSubro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlanketWaiverOfSubro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trWaiverOfSubroRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trWaiverOfSubroRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkWaiverofSubro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWaiverofSubro As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblWaiverOfSubro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaiverOfSubro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trNumberOfWaiversRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNumberOfWaiversRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtNumberOfWaivers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumberOfWaivers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trExclusionOfAmishWorkers_row control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trExclusionOfAmishWorkers_row As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkExclusionOfAmishWorkers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExclusionOfAmishWorkers As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblExclusionOfAmishWorkers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExclusionOfAmishWorkers As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trExclusionOfExecutiveOfficer_row control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trExclusionOfExecutiveOfficer_row As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkExclusionOfExecutiveOfficer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExclusionOfExecutiveOfficer As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblExclusionOfExecutiveOfficer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExclusionOfExecutiveOfficer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInfo1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trExclusionOfSoleProprietorsEtc_IL_row control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trExclusionOfSoleProprietorsEtc_IL_row As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkExclusionOfSoleProprietorsEtc_IL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExclusionOfSoleProprietorsEtc_IL As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblExclusionOfSoleProprietorsEtc_IL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExclusionOfSoleProprietorsEtc_IL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trRejectionOfCoverageEndorsementRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRejectionOfCoverageEndorsementRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkRejectionOfCoverageEndorsement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRejectionOfCoverageEndorsement As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblRejectionOfCoverageEndorsement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectionOfCoverageEndorsement As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveAndRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAndRate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEmailForUWAssistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmailForUWAssistance As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hdnAccordGenInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccordGenInfo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAccordLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccordLoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAccordClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccordClass As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAccordClassList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccordClassList As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAccordEndorsements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccordEndorsements As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
