name: Build and Push Dev Docker Images for tagged versions

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up metadata
        id: meta
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set lowercase owner name
        run: echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./api.Dockerfile
          # Only push when not a PR
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.OWNER }}/agentc-api:latest
            ghcr.io/${{ env.OWNER }}/agentc-api:build-${{ github.run_number }}


      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./src/realtime_client
          file: ./client.Dockerfile
          # Only push when not a PR
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.OWNER }}/agentc-client:latest
            ghcr.io/${{ env.OWNER }}/agentc-client:build-${{ github.run_number }}
