'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_CGL_PFSummary

    '''<summary>
    '''lblMainAccord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainAccord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPremiumMainAccord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPremiumMainAccord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImageDateAndPremChangeLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageDateAndPremChangeLine As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTranEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTranEffDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnualPremChg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnualPremChg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPhName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trCareOf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCareOf As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCareOf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCareOf As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPhAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuoteNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuoteNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEffectiveDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExpirationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpirationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFullPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFullPremium As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblPolicyCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPolicyCoverages As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rowGenAgg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowGenAgg As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdGenAggLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdGenAggLimit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdGenAggPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdGenAggPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowProdCompOpsAgg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowProdCompOpsAgg As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ProdCompOpsAggLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProdCompOpsAggLimit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ProdCompOpsAggLimitQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProdCompOpsAggLimitQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowPersAndAdInjury control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowPersAndAdInjury As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdPersAndAdInjuryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPersAndAdInjuryLimit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdPersAndAdInjuryLimitQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPersAndAdInjuryLimitQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowOccLiability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowOccLiability As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdOccLiabilityLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdOccLiabilityLimit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdOccLiabilityLimitQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdOccLiabilityLimitQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowDamageToPremsRented control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDamageToPremsRented As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdDamageToPremsRentedLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDamageToPremsRentedLimit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdDamageToPremsRentedLimitQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDamageToPremsRentedLimitQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowMedicalExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowMedicalExpenses As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdMedicalExpensesLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMedicalExpensesLimit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdMedicalExpensesLimitQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMedicalExpensesLimitQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowBusMasterEnhancement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBusMasterEnhancement As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdBusMasterEnhancementQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBusMasterEnhancementQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowGlPlusEnhancement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowGlPlusEnhancement As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''GlPlusEnhancementQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GlPlusEnhancementQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowBlanketWaiverOfSubro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBlanketWaiverOfSubro As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdBlanketWaiverOfSubroText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBlanketWaiverOfSubroText As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdBlanketWaiverOfSubroQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBlanketWaiverOfSubroQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''pnlGenLibDeductible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGenLibDeductible As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdGenLibDeductibleQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdGenLibDeductibleQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''GenLibDeductibleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenLibDeductibleType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GenLibDeductibleAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenLibDeductibleAmount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GenLibDeductibleBasis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenLibDeductibleBasis As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rowAdditionalInsureds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowAdditionalInsureds As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdAdditionalInsuredsPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdAdditionalInsuredsPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowEmployeeBenefitsLiability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowEmployeeBenefitsLiability As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''EmpBLibNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmpBLibNum As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tdEmployeeBenefitsLiabilityQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdEmployeeBenefitsLiabilityQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowEPLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowEPLI As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdEPLIQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdEPLIQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowHiredAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowHiredAuto As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdHiredAutoQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdHiredAutoQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowNonOwnedAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowNonOwnedAuto As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdNonOwnedAutoQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdNonOwnedAutoQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowStopGap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowStopGap As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdStopGapQuotedPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdStopGapQuotedPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''pnlLiquorLiability_IN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLiquorLiability_IN As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdLiquorLiabilityQuotedPremium_IN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLiquorLiabilityQuotedPremium_IN As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LiquorLiabilityOccLimit_IN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityOccLimit_IN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiquorLiabilityClass_IN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityClass_IN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiquorLiabilityLSales_IN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityLSales_IN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlLiquorLiability_OH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLiquorLiability_OH As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdLiquorLiabilityQuotedPremium_OH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLiquorLiabilityQuotedPremium_OH As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LiquorLiabilityOccLimit_OH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityOccLimit_OH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiquorLiabilityClass_OH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityClass_OH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiquorLiabilitySales_OH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilitySales_OH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlLiquorLiability_IL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLiquorLiability_IL As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdLiquorLiabilityQuotedPremium_IL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLiquorLiabilityQuotedPremium_IL As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''LiquorLiabilityOccLimit_IL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityOccLimit_IL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiquorLiabilityClass_IL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityClass_IL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiquorLiabilityLSales_IL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiquorLiabilityLSales_IL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlContractorsHomeRepairAndRemodeling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlContractorsHomeRepairAndRemodeling As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdContractorsHomeRepairAndRemodelingLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdContractorsHomeRepairAndRemodelingLimit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdContractorsHomeRepairAndRemodelingPremium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdContractorsHomeRepairAndRemodelingPremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''pnlProfessionalLiability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProfessionalLiability As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rowProfessionalLiability_CP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowProfessionalLiability_CP As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PL_CP_Num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PL_CP_Num As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tdPL_CP_Premium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPL_CP_Premium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowProfessionalLiability_FP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowProfessionalLiability_FP As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PL_FP_Num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PL_FP_Num As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tdPL_FP_Premium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPL_FP_Premium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowProfessionalLiability_PP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowProfessionalLiability_PP As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''PL_PP_Num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PL_PP_Num As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tdPL_PP_Premium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPL_PP_Premium As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowMinimumPremiumAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowMinimumPremiumAdjustment As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdMinimum_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMinimum_Prem As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowPremisesAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowPremisesAdjustment As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdPremises_MinPremAdj_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdPremises_MinPremAdj_Prem As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''rowProductsAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowProductsAdjustment As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdProducts_MinPremAdj_Prem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdProducts_MinPremAdj_Prem As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ctlPolicyDiscounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPolicyDiscounts As Global.IFM.VR.Web.PolicyDiscounts

    '''<summary>
    '''tblLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblLocations As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tblClassifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblClassifications As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tblLossHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblLossHistory As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField
End Class
