'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctl_WorkflowManager_Quote_CGL
    
    '''<summary>
    '''ctlEffectiveDateChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEffectiveDateChecker As Global.IFM.VR.Web.ctlEffectiveDateChecker
    
    '''<summary>
    '''ctlUWQuestionsPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlUWQuestionsPopup As Global.IFM.VR.Web.ctlUWQuestionsPopup
    
    '''<summary>
    '''ctlRiskGradeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlRiskGradeSearch As Global.IFM.VR.Web.ctlRiskGradeSearch
    
    '''<summary>
    '''ctlDisplayDiamondRatingErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDisplayDiamondRatingErrors As Global.IFM.VR.Web.ctlDisplayDiamondRatingErrors
    
    '''<summary>
    '''ctlTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlTreeView As Global.IFM.VR.Web.ctlTreeView
    
    '''<summary>
    '''ctlIsuredList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlIsuredList As Global.IFM.VR.Web.ctlIsuredList
    
    '''<summary>
    '''ctl_CGL_PolicyLevelCoverages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_CGL_PolicyLevelCoverages As Global.IFM.VR.Web.ctl_CGL_PolicyLevelCoverages
    
    '''<summary>
    '''ctl_CGL_LocationsWF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_CGL_LocationsWF As Global.IFM.VR.Web.ctl_CGL_LocationsWF
    
    '''<summary>
    '''ctl_AttachmentUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_AttachmentUpload As Global.IFM.VR.Web.ctl_AttachmentUpload
    
    '''<summary>
    '''ctl_CGL_QuoteSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_CGL_QuoteSummary As Global.IFM.VR.Web.ctl_CGL_QuoteSummary
    
    '''<summary>
    '''Ctl_CGL_PFSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ctl_CGL_PFSummary As Global.IFM.VR.Web.ctl_CGL_PFSummary
    
    '''<summary>
    '''ctl_CGL_IRPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_CGL_IRPM As Global.IFM.VR.Web.ctlCommercial_IRPM
    
    '''<summary>
    '''ctl_CGL_EmailUW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_CGL_EmailUW As Global.IFM.VR.Web.ctl_Comm_EmailUW
    
    '''<summary>
    '''ctlProposalSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlProposalSelection As Global.IFM.VR.Web.ctlProposalSelection
    
    '''<summary>
    '''ctl_Comm_NewQuoteForClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl_Comm_NewQuoteForClient As Global.IFM.VR.Web.ctl_Comm_NewQuoteForClient
End Class
